// Privacy note: Never track PII. Anonymize file names, URLs, and user inputs.

type GTagEvent = {
  action: string
  category: string
  label?: string
  value?: number
}

type ToolEvent =
  | 'json_beautify'
  | 'json_minify'
  | 'json_copy'
  | 'json_download'
  | 'json_schema_validate'
  | 'json_schema_template'
  | 'json_generate_sample'
  | 'json_search'
  | 'json_to_typescript'
  | 'json_typescript_copy'
  | 'json_compare'
  | 'json_path_copy'
  | 'json_history_load'
  | 'json_history_delete'
  | 'json_history_clear'
  | 'json_history_favorite'
  | 'json_to_csv_convert'
  | 'json_to_csv_copy'
  | 'json_to_csv_download'
  | 'split_bill_add_person'
  | 'split_bill_remove_person'
  | 'split_bill_share'
  | 'split_bill_copy'
  | 'split_bill_reset'
  | 'split_bill_currency_change'
  | 'split_bill_currency_converter_toggled'
  | 'split_bill_scan_receipt'
  | 'split_bill_upload_receipt'
  | 'split_bill_ocr_success'
  | 'split_bill_ocr_error'
  | 'split_bill_save'
  | 'split_bill_view'
  | 'split_bill_view_error'
  | 'split_bill_payment_update'
  | 'split_bill_copy_link'
  | 'split_bill_export_pdf'
  | 'split_bill_export_csv'
  | 'split_bill_export'
  | 'split_bill_share_summary'
  | 'split_bill_draft_restored'
  | 'split_bill_payment_request'
  | 'split_bill_template_saved'
  | 'split_bill_template_loaded'
  | 'qr_code_type_change'
  | 'qr_code_download'
  | 'qr_code_copy'
  | 'qr_logo_upload'
  | 'qr_style_preset'
  | 'qr_bulk_generate'
  | 'qr_history_save'
  | 'qr_history_load'
  | 'qr_history_favorite'
  | 'qr_history_delete'
  | 'qr_history_clear'
  | 'qr_history_export'
  | 'qr_history_import'
  | 'qr_scan_validate'
  | 'qr_advanced_type_generate'
  | 'qr_batch_export'
  | 'qr_print_template'
  | 'qr_export_png_dpi'
  | 'qr_export_jpeg'
  | 'qr_export_webp'
  | 'qr_export_pdf'
  | 'qr_export_batch_zip'
  | 'qr_export_template_selected'
  | 'qr_scanner_webcam_start'
  | 'qr_scanner_webcam_success'
  | 'qr_scanner_file_upload'
  | 'qr_scanner_file_success'
  | 'qr_validate_run'
  | 'qr_validate_score'
  | 'qr_code_type_email_generate'
  | 'qr_code_type_sms_generate'
  | 'qr_code_type_phone_generate'
  | 'qr_code_type_whatsapp_generate'
  | 'qr_code_type_geo_generate'
  | 'qr_code_type_event_generate'
  | 'qr_code_type_appstore_generate'
  | 'qr_code_type_social_generate'
  | 'qr_tracking_enabled'
  | 'qr_tracking_view_analytics'
  | 'diff_compare'
  | 'diff_view_change'
  | 'markdown_preview_toggle'
  | 'markdown_export'
  | 'url_shorten'
  | 'qr_generate'
  | 'file_upload'
  | 'password_generate'
  | 'password_generate_random'
  | 'password_generate_diceware'
  | 'password_generate_pronounceable'
  | 'password_generate_template'
  | 'password_bulk_generate'
  | 'password_bulk_export'
  | 'password_copy'
  | 'password_download'
  | 'password_pwned_check'
  | 'password_history_export'
  | 'password_strength_analyze'
  | 'text_transformer_open'
  | 'unit_converter_open'
  | 'unit_converter_convert'
  | 'unit_converter_swap'
  | 'unit_converter_favorite_add'
  | 'unit_converter_favorite_remove'
  | 'unit_converter_favorite_load'
  | 'unit_converter_history_clear'
  | 'unit_converter_history_export'
  | 'unit_converter_history_replay'
  | 'unit_converter_chain_add_step'
  | 'unit_converter_chain_remove_step'
  | 'unit_converter_chain_clear'
  | 'unit_converter_chain_reorder'
  | 'unit_converter_chain_save'
  | 'unit_converter_chain_load'
  | 'unit_converter_chain_delete'
  | 'unit_converter_chain_export'
  | 'unit_converter_preset_load'
  | 'pomodoro_timer_view'
  | 'pomodoro_start'
  | 'pomodoro_pause'
  | 'pomodoro_reset'
  | 'pomodoro_complete'
  | 'pomodoro_break_complete'
  | 'pomodoro_mode_change'
  | 'pomodoro_task_add'
  | 'pomodoro_task_delete'
  | 'pomodoro_task_toggle'
  | 'pomodoro_settings_save'
  | 'tool_card_click'
  | 'search_query'
  | 'category_filter'
  | 'view_mode_toggle'
  | 'gradient_generator_view'
  | 'gradient_generator_add_color_stop'
  | 'gradient_generator_remove_color_stop'
  | 'gradient_generator_apply_preset'
  | 'gradient_generator_copy_css'
  | 'gradient_generator_download_png'
  | 'gradient_generator_randomize'
  | 'gradient_generator_reverse'
  | 'currency_converter_open'
  | 'currency_converter_convert'
  | 'currency_converter_swap'
  | 'currency_converter_rates_loaded'
  | 'currency_converter_favorite_add'
  | 'currency_converter_favorite_remove'
  | 'currency_converter_favorite_load'
  | 'stopwatch_timer_open'
  | 'stopwatch_start'
  | 'stopwatch_pause'
  | 'stopwatch_reset'
  | 'stopwatch_lap'
  | 'stopwatch_export_csv'
  | 'stopwatch_export_json'
  | 'stopwatch_save_session'
  | 'timer_add'
  | 'timer_remove'
  | 'timer_start'
  | 'timer_pause'
  | 'timer_reset'
  | 'timer_complete'
  | 'timer_preset_save'
  | 'timer_preset_load'
  | 'timer_preset_delete'
  | 'mode_change'
  | 'notification_permission_request'
  | 'tally_counter_open'
  | 'tally_counter_increment'
  | 'tally_counter_decrement'
  | 'tally_counter_reset'
  | 'tally_counter_add'
  | 'tally_counter_remove'
  | 'tally_counter_set_step'
  | 'api_tester_open'
  | 'api_tester_send_request'
  | 'api_tester_save_preset'
  | 'api_tester_load_preset'
  | 'api_tester_delete_preset'
  | 'api_tester_copy_response'
  | 'api_tester_method_change'
  | 'api_tester_add_query_param'
  | 'api_tester_use_api_key_auth'
  | 'api_tester_keyboard_shortcut_used'
  | 'api_tester_tab_change'
  | 'api_tester_environment_created'
  | 'api_tester_environment_updated'
  | 'api_tester_environment_deleted'
  | 'api_tester_environment_duplicated'
  | 'api_tester_environment_activated'
  | 'api_tester_environment_variable_added'
  | 'prompt_formatter_open'
  | 'prompt_formatter_template_apply'
  | 'prompt_formatter_format'
  | 'prompt_formatter_copy'
  | 'prompt_formatter_download'
  | 'prompt_formatter_optimize'
  | 'prompt_formatter_clear'
  | 'prompt_formatter_model_change'
  | 'json_markdown_copy'
  | 'json_markdown_download'
  | 'browser_fingerprint_open'
  | 'browser_fingerprint_section_toggle'
  | 'browser_fingerprint_copy'
  | 'browser_fingerprint_copy_all'
  | 'color_contrast_open'
  | 'color_contrast_swap'
  | 'color_contrast_copy'
  | 'color_contrast_random'
  | 'color_contrast_change_foreground'
  | 'color_contrast_change_background'
  | 'recent_tool_click'
  | 'recent_tools_cleared'
  | 'clipboard_paste'
  | 'clipboard_format'
  | 'clipboard_case_transform'
  | 'clipboard_copy_formatted'
  | 'clipboard_download'
  | 'clipboard_reset'
  | 'clipboard_load_history'
  | 'clipboard_clear_history'
  | 'screenshot_diff_open'
  | 'screenshot_diff_upload_image1'
  | 'screenshot_diff_upload_image2'
  | 'screenshot_diff_compare'
  | 'screenshot_diff_reset'
  | 'screenshot_diff_download'
  | 'json_schema_generate'
  | 'json_schema_copy'
  | 'json_schema_download'
  | 'password_strength_open'
  | 'password_strength_checked'
  | 'password_strength_copy'
  | 'date_formatter_open'
  | 'date_parse'
  | 'date_format'
  | 'date_convert'
  | 'date_copy'
  | 'date_set_current'
  | 'cron_expression_open'
  | 'cron_expression_manual_edit'
  | 'cron_expression_field_change'
  | 'cron_expression_pattern_select'
  | 'cron_expression_copy'
  | 'cron_expression_export'
  | 'cron_builder_preset'
  | 'cron_builder_platform'
  | 'cron_builder_copy'
  | 'cron_builder_download'
  | 'cron_builder_reset'
  | 'jwt_debugger_open'
  | 'jwt_debugger_decode'
  | 'jwt_debugger_verify'
  | 'jwt_debugger_generate'
  | 'jwt_debugger_copy'
  | 'jwt_debugger_history_load'
  | 'jwt_debugger_history_delete'
  | 'jwt_debugger_history_clear'
  | 'jwt_debugger_history_favorite'
  | 'favicon_upload_image'
  | 'favicon_select_emoji'
  | 'favicon_generate'
  | 'favicon_download_ico'
  | 'favicon_download_png'
  | 'favicon_copy_html'
  | 'color_picker_open'
  | 'color_picker_change'
  | 'color_picker_random'
  | 'color_picker_copy'
  | 'color_picker_copy_palette'
  | 'color_picker_palette_type'
  | 'csv_excel_convert'
  | 'csv_excel_download'
  | 'csv_excel_error'
  | 'csv_merger_upload'
  | 'csv_merger_merge'
  | 'csv_merger_split'
  | 'csv_merger_download'
  | 'csv_merger_error'
  | 'task_timer_open'
  | 'task_timer_session_start'
  | 'task_timer_session_end'
  | 'task_timer_session_delete'
  | 'task_timer_add'
  | 'task_timer_start'
  | 'task_timer_pause'
  | 'task_timer_reset'
  | 'task_timer_remove'
  | 'task_timer_export_csv'
  | 'task_timer_export_json'
  | 'clipboard_history_open'
  | 'clipboard_history_start_monitoring'
  | 'clipboard_history_stop_monitoring'
  | 'clipboard_history_add_item'
  | 'clipboard_history_copy_item'
  | 'clipboard_history_toggle_pin'
  | 'clipboard_history_delete_item'
  | 'clipboard_history_clear_all'
  | 'speed_test_open'
  | 'speed_test_start'
  | 'speed_test_complete'
  | 'speed_test_error'
  | 'image_metadata_open'
  | 'image_metadata_parse'
  | 'image_metadata_clear'
  | 'image_metadata_copy'
  | 'image_metadata_download'
  | 'ai_caption_open'
  | 'ai_caption_upload'
  | 'ai_caption_generate'
  | 'ai_caption_copy'
  | 'ai_caption_error'
  | 'ai_snippet_open'
  | 'ai_snippet_generate'
  | 'ai_snippet_copy'
  | 'ai_snippet_error'
  | 'ai_json_open'
  | 'ai_json_analyze'
  | 'ai_json_copy'
  | 'ai_json_error'
  | 'uuid_generator_open'
  | 'uuid_generate_single'
  | 'uuid_generate_bulk'
  | 'uuid_validate'
  | 'uuid_copy'
  | 'uuid_copy_bulk'
  | 'batch_rename_open'
  | 'batch_rename_upload'
  | 'batch_rename_remove_file'
  | 'batch_rename_clear'
  | 'batch_rename_reset'
  | 'batch_rename_apply'
  | 'text_summarizer_open'
  | 'text_summarizer_summarize'
  | 'text_summarizer_copy'
  | 'text_summarizer_download'
  | 'text_summarizer_error'
  | 'text_similarity_open'
  | 'text_similarity_compare'
  | 'text_similarity_clear'
  | 'text_similarity_load_example'
  | 'text_similarity_copy_result'
  | 'ai_text_rewriter_open'
  | 'ai_text_rewriter_rewrite'
  | 'ai_text_rewriter_copy'
  | 'ai_text_rewriter_clear'
  | 'ai_text_rewriter_load_example'
  | 'ai_text_rewriter_error'
  | 'ai_command_explainer_open'
  | 'ai_command_explainer_explain'
  | 'ai_command_explainer_copy'
  | 'ai_command_explainer_load_example'
  | 'ai_command_explainer_error'
  | 'grammar_checker_open'
  | 'grammar_checker_check'
  | 'grammar_checker_apply_fix'
  | 'grammar_checker_error'
  | 'keyword_density_open'
  | 'keyword_density_analyze'
  | 'keyword_density_copy'
  | 'keyword_density_clear'
  | 'keyword_density_export'
  | 'percentage_calculator_open'
  | 'percentage_calculator_calculate'
  | 'percentage_calculator_mode_change'
  | 'percentage_calculator_copy'
  | 'percentage_calculator_clear'
  | 'invoice_generator_open'
  | 'invoice_generator_add_item'
  | 'invoice_generator_remove_item'
  | 'invoice_generator_save'
  | 'invoice_generator_load'
  | 'invoice_generator_delete'
  | 'invoice_generator_new'
  | 'invoice_generator_print'
  | 'invoice_generator_download'
  | 'loan_calculator_open'
  | 'loan_calculator_calculate'
  | 'loan_calculator_extra_payment'
  | 'loan_calculator_toggle_schedule'
  | 'loan_calculator_add_comparison'
  | 'loan_calculator_remove_comparison'
  | 'loan_calculator_currency_change'
  | 'steganography_open'
  | 'steganography_encode'
  | 'steganography_decode'
  | 'steganography_copy'
  | 'steganography_error'
  | 'timezone_converter_open'
  | 'timezone_converter_add'
  | 'timezone_converter_remove'
  | 'timezone_converter_time_change'
  | 'timezone_converter_favorite_add'
  | 'timezone_converter_favorite_remove'
  | 'timezone_converter_favorite_load'
  | 'yaml_json_converter_open'
  | 'yaml_json_converter_convert'
  | 'yaml_json_converter_swap'
  | 'yaml_json_converter_copy'
  | 'yaml_json_converter_download'
  | 'yaml_json_converter_clear'
  | 'yaml_json_converter_load_example'
  | 'file_inspector_open'
  | 'file_inspector_analyze'
  | 'file_inspector_clear'
  | 'file_inspector_copy'
  | 'regex_tester_open'
  | 'regex_tester_test'
  | 'regex_tester_pattern_load'
  | 'regex_tester_copy'
  | 'regex_tester_download'
  | 'regex_tester_clear'
  | 'regex_tester_match_found'
  | 'regex_tester_flag_toggled'
  | 'regex_tester_pattern_loaded'
  | 'regex_tester_cleared'
  | 'regex_tester_pattern_copied'
  | 'regex_tester_code_copied'
  | 'sql_formatter_formatted'
  | 'sql_formatter_minified'
  | 'sql_formatter_copied'
  | 'sql_formatter_cleared'
  | 'sql_formatter_example_loaded'
  | 'lorem_ipsum_generated'
  | 'lorem_ipsum_copied'
  | 'lorem_ipsum_cleared'
  | 'word_counter_text_changed'
  | 'word_counter_cleared'
  | 'word_counter_copied'
  | 'word_counter_sample_loaded'
  | 'word_counter_keywords_viewed'
  | 'character_map_character_copied'
  | 'character_map_category_changed'
  | 'character_map_searched'
  | 'placeholder_generator_size_changed'
  | 'placeholder_generator_preset_selected'
  | 'placeholder_generator_color_changed'
  | 'placeholder_generator_copied'
  | 'placeholder_generator_downloaded'
  | 'image_format_converter_upload'
  | 'image_format_converter_convert'
  | 'image_format_converter_download'
  | 'image_format_converter_format_change'
  | 'qr_code_scanner_upload'
  | 'qr_code_scanner_success'
  | 'qr_code_scanner_no_code'
  | 'qr_code_scanner_webcam_start'
  | 'qr_code_scanner_webcam_success'
  | 'qr_code_scanner_webcam_stop'
  | 'qr_code_scanner_copy'
  | 'qr_code_scanner_clear_history'
  | 'qr_code_scanner_delete'
  | 'tool_search_open'
  | 'tool_search_select'
  | 'signature_generator_view'
  | 'signature_generator_download'
  | 'signature_generator_copy'
  | 'signature_generator_clear'
  | 'signature_generator_randomize'
  | 'tip_calculator_open'
  | 'tip_calculator_preset'
  | 'tip_calculator_calculate'
  | 'tip_calculator_copy'
  | 'tip_calculator_clear'
  | 'age_calculator_open'
  | 'age_calculator_calculate'
  | 'age_calculator_clear'
  | 'age_calculator_copy'
  | 'file_verifier_open'
  | 'file_verifier_hash'
  | 'file_verifier_verify'
  | 'file_verifier_clear'
  | 'file_verifier_copy'
  | 'file_verifier_algorithm_change'
  | 'jwt_decoder_open'
  | 'jwt_decoder_decode'
  | 'jwt_decoder_clear'
  | 'jwt_decoder_copy'
  | 'dockerfile_formatter_open'
  | 'dockerfile_formatter_format'
  | 'dockerfile_formatter_clear'
  | 'dockerfile_formatter_copy'
  | 'svg_optimizer_open'
  | 'svg_optimizer_optimize'
  | 'svg_optimizer_clear'
  | 'svg_optimizer_copy'
  | 'svg_optimizer_download'
  | 'photo_editor_upload'
  | 'photo_editor_premium_upsell'
  | 'photo_editor_filter_apply'
  | 'photo_editor_adjustment'
  | 'photo_editor_rotate'
  | 'photo_editor_flip'
  | 'photo_editor_export'
  | 'photo_editor_reset'
  | 'photo_editor_ai_generate_start'
  | 'photo_editor_ai_generate_success'
  | 'photo_editor_ai_generate_error'
  | 'image_to_pdf_opened'
  | 'images_added'
  | 'pdf_generation_started'
  | 'pdf_generated'
  | 'pdf_generation_failed'
  | 'graphql_playground_open'
  | 'graphql_query_execute'
  | 'graphql_query_error'
  | 'graphql_response_copy'
  | 'graphql_response_download'
  | 'graphql_history_load'
  | 'graphql_history_clear'
  | 'graphql_sample_load'
  | 'ssl_checker_open'
  | 'ssl_check_complete'
  | 'ssl_check_error'
  | 'ssl_report_copy'
  | 'meme_template_select'
  | 'meme_custom_upload'
  | 'meme_generate'
  | 'meme_generate_error'
  | 'meme_download'
  | 'meme_reset'
  | 'resume_builder_open'
  | 'resume_section_change'
  | 'resume_template_change'
  | 'resume_personal_info_update'
  | 'resume_experience_add'
  | 'resume_experience_remove'
  | 'resume_experience_achievement_add'
  | 'resume_experience_achievement_optimize'
  | 'resume_education_add'
  | 'resume_education_remove'
  | 'resume_skills_add_category'
  | 'resume_skills_remove_category'
  | 'resume_skills_quick_start'
  | 'resume_project_add'
  | 'resume_project_remove'
  | 'resume_save'
  | 'resume_auto_save'
  | 'resume_load'
  | 'resume_export_pdf'
  | 'resume_export_simple_pdf'
  | 'resume_export_json'
  | 'resume_ats_score_calculated'
  | 'resume_sample_data_toggle'
  | 'resume_persona_view'
  | 'resume_persona_load_sample'
  | 'cover_letter_builder_open'
  | 'cover_letter_loaded_from_storage'
  | 'cover_letter_form_updated'
  | 'cover_letter_template_changed'
  | 'cover_letter_exported'
  | 'cover_letter_imported'
  | 'cover_letter_cleared'
  | 'cover_letter_ai_suggestion_requested'
  | 'cover_letter_ai_suggestion_applied'
  | 'cover_letter_ai_tone_checked'
  | 'cover_letter_ai_content_improved'
  | 'icon_search_open'
  | 'icon_search_query'
  | 'icon_select'
  | 'icon_favorite'
  | 'icon_download_svg'
  | 'icon_download_png'
  | 'icon_copy_svg'
  | 'icon_copy_react'
  | 'icon_customize'
  | 'mockup_generator_open'
  | 'mockup_image_upload'
  | 'mockup_device_select'
  | 'mockup_orientation_toggle'
  | 'mockup_generate_success'
  | 'mockup_export'
  | 'mockup_background_change'
  | 'privacy_policy_generator_open'
  | 'privacy_policy_document_type_select'
  | 'privacy_policy_industry_select'
  | 'privacy_policy_jurisdiction_select'
  | 'privacy_policy_option_toggle'
  | 'privacy_policy_copy'
  | 'privacy_policy_download_html'
  | 'privacy_policy_download_pdf'
  | 'code_converter_open'
  | 'code_converter_source_select'
  | 'code_converter_target_select'
  | 'code_converter_option_toggle'
  | 'code_converter_convert'
  | 'code_converter_success'
  | 'code_converter_error'
  | 'code_converter_copy'
  | 'code_converter_download'
  | 'code_converter_swap'
  | 'webhook_tester_open'
  | 'webhook_tester_create'
  | 'webhook_tester_copy_url'
  | 'webhook_tester_request_received'
  | 'webhook_tester_inspect'

// Type-safe gtag wrapper
declare global {
  interface Window {
    gtag?: (command: 'config' | 'event', targetId: string, config?: Record<string, unknown>) => void
  }
}

const GA_MEASUREMENT_ID =
  typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID : undefined

// Check if GA is enabled (production + ID exists)
const isGAEnabled = (): boolean => {
  return Boolean(GA_MEASUREMENT_ID && typeof window !== 'undefined' && window.gtag)
}

// Log warning in development when GA ID is missing
if (
  typeof window !== 'undefined' &&
  typeof process !== 'undefined' &&
  process.env.NODE_ENV === 'development' &&
  !GA_MEASUREMENT_ID
) {
  console.warn(
    '[Analytics] GA4 Measurement ID not found. Set NEXT_PUBLIC_GA_MEASUREMENT_ID in .env.local'
  )
}

/**
 * Track custom tool events
 * @param eventName - Tool-specific event name
 * @param params - Additional parameters (no PII)
 */
export const trackToolEvent = (
  eventName: ToolEvent,
  params?: Record<string, string | number | boolean | string[]>
): void => {
  if (!isGAEnabled()) {
    if (process.env.NODE_ENV === 'development') {
      console.log('[Analytics Dev]', eventName, params)
    }
    return
  }

  window.gtag?.('event', eventName, {
    ...params,
    timestamp: Date.now(),
  })
}

/**
 * Track generic events with category/label structure
 */
export const trackEvent = ({ action, category, label, value }: GTagEvent): void => {
  if (!isGAEnabled()) {
    if (process.env.NODE_ENV === 'development') {
      console.log('[Analytics Dev]', { action, category, label, value })
    }
    return
  }

  window.gtag?.('event', action, {
    event_category: category,
    event_label: label,
    value,
  })
}

/**
 * Track page views (Next.js handles this automatically, but available if needed)
 */
export const trackPageView = (url: string): void => {
  if (!isGAEnabled()) return
  if (!GA_MEASUREMENT_ID) return

  window.gtag?.('config', GA_MEASUREMENT_ID, {
    page_path: url,
  })
}

/**
 * Report Web Vitals to GA4
 * Usage: import { useReportWebVitals } from 'next/web-vitals'
 */
export const reportWebVitals = (metric: {
  id: string
  name: string
  label: string
  value: number
}): void => {
  if (!isGAEnabled()) return

  window.gtag?.('event', metric.name, {
    value: Math.round(metric.name === 'CLS' ? metric.value * 1000 : metric.value),
    event_label: metric.id,
    non_interaction: true,
  })
}
