import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { toast } from 'sonner'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import GradientGeneratorPage from '../page'

let queryClient: QueryClient

const renderPage = () =>
  render(
    <QueryClientProvider client={queryClient}>
      <GradientGeneratorPage />
    </QueryClientProvider>
  )

// Mock sonner toast
vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
  },
}))

// Mock analytics
vi.mock('@/lib/services/analytics', () => ({
  trackToolEvent: vi.fn(),
  trackEvent: vi.fn(),
}))

// Mock SEO components that use Next.js Link
vi.mock('@/components/ui/social-share', () => ({
  SocialShare: () => null,
}))

vi.mock('@/components/ui/related-tools', () => ({
  RelatedTools: () => null,
}))

vi.mock('@/components/ui/tool-rating', () => ({
  ToolRating: () => null,
}))

describe('Gradient Generator Page - Component Tests', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should render gradient generator page', () => {
    renderPage()

    expect(
      screen.getByRole('heading', { name: 'Gradient Generator', level: 1 })
    ).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Preview', level: 2 })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Gradient Controls', level: 2 })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Gradient Presets', level: 2 })).toBeInTheDocument()
  })

  it('should display gradient type buttons', () => {
    renderPage()

    expect(screen.getByRole('button', { name: 'linear' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'radial' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'conic' })).toBeInTheDocument()
  })

  it('should have linear gradient selected by default', () => {
    renderPage()

    const _linearButton = screen.getByRole('button', { name: 'linear' })
    // Check that linear gradient CSS is generated by default
    // Use getAllByText to handle multiple matches, then filter for the <pre> element
    const cssOutputs = screen.getAllByText(/background:/)
    const cssOutput = cssOutputs.find((el) => el.tagName === 'PRE')
    expect(cssOutput).toBeDefined()
    expect(cssOutput?.textContent).toContain('linear-gradient')
  })

  it('should display default color stops', () => {
    renderPage()

    // Should have 2 default color stops
    const colorInputs = screen.getAllByRole('textbox')
    expect(colorInputs.length).toBeGreaterThanOrEqual(2)
  })

  it('should display angle control for linear gradient', () => {
    renderPage()

    expect(screen.getByText(/Angle:/)).toBeInTheDocument()
  })

  it('should display action buttons', () => {
    renderPage()

    expect(screen.getByRole('button', { name: /Copy CSS/ })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Download PNG/ })).toBeInTheDocument()
  })

  it('should switch gradient types', async () => {
    renderPage()

    const radialButton = screen.getByRole('button', { name: 'radial' })
    await userEvent.click(radialButton)

    // Angle control should not be visible for radial gradients
    expect(screen.queryByText(/Angle:/)).not.toBeInTheDocument()
  })

  it('should add a new color stop', async () => {
    renderPage()

    const addButton = screen.getByRole('button', { name: /Add/ })
    const initialColorInputs = screen.getAllByRole('textbox').length

    await userEvent.click(addButton)

    const newColorInputs = screen.getAllByRole('textbox').length
    expect(newColorInputs).toBe(initialColorInputs + 1)
  })

  it('should copy CSS to clipboard', async () => {
    renderPage()

    const copyButton = screen.getByRole('button', { name: /Copy CSS/ })
    await userEvent.click(copyButton)

    await waitFor(() => {
      expect(navigator.clipboard.writeText).toHaveBeenCalled()
    })
  })

  it('should randomize gradient', async () => {
    renderPage()

    const randomizeButton = screen.getAllByRole('button').find((btn) => {
      const svg = btn.querySelector('svg')
      return svg?.getAttribute('class')?.includes('lucide-shuffle')
    })

    expect(randomizeButton).toBeInTheDocument()
    if (randomizeButton) {
      await userEvent.click(randomizeButton)
      // Gradient should be randomized (visual change, hard to test)
    }
  })

  it('should reverse gradient', () => {
    renderPage()

    const reverseButton = screen.getAllByRole('button').find((btn) => {
      const svg = btn.querySelector('svg')
      return svg?.getAttribute('class')?.includes('lucide-rotate-ccw')
    })

    expect(reverseButton).toBeInTheDocument()
  })

  it('should toggle preview background', async () => {
    renderPage()

    // Find the preview background toggle button
    const toggleButtons = screen.getAllByRole('button')
    const previewToggle = toggleButtons.find((btn) => {
      return btn.querySelector('svg.lucide-sun') || btn.querySelector('svg.lucide-moon')
    })

    expect(previewToggle).toBeInTheDocument()
    if (previewToggle) {
      await userEvent.click(previewToggle)
      // Background should toggle (visual change)
    }
  })

  it('should prevent removing color stops when only 2 remain', () => {
    renderPage()

    // Try to find and click remove button on a color stop
    const deleteButtons = screen.getAllByRole('button').filter((btn) => {
      const svg = btn.querySelector('svg')
      return svg?.getAttribute('class')?.includes('lucide-trash-2')
    })

    // If there are only 2 color stops, no delete buttons should be visible
    expect(deleteButtons.length).toBe(0)
  })
})

describe('Gradient Generator - CSS Generation', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should generate correct linear gradient CSS', () => {
    renderPage()

    // Check that the CSS output contains "linear-gradient"
    // Use getAllByText to handle multiple matches, then filter for the <pre> element
    const cssOutputs = screen.getAllByText(/background:/)
    const cssOutput = cssOutputs.find((el) => el.tagName === 'PRE')
    expect(cssOutput).toBeDefined()
    expect(cssOutput?.textContent).toContain('linear-gradient')
  })

  it('should generate radial gradient CSS when radial type is selected', async () => {
    renderPage()

    const radialButton = screen.getByRole('button', { name: 'radial' })
    await userEvent.click(radialButton)

    // Use getAllByText to handle multiple matches, then filter for the <pre> element
    const cssOutputs = screen.getAllByText(/background:/)
    const cssOutput = cssOutputs.find((el) => el.tagName === 'PRE')
    expect(cssOutput).toBeDefined()
    expect(cssOutput?.textContent).toContain('radial-gradient')
  })

  it('should generate conic gradient CSS when conic type is selected', async () => {
    renderPage()

    const conicButton = screen.getByRole('button', { name: 'conic' })
    await userEvent.click(conicButton)

    // Use getAllByText to handle multiple matches, then filter for the <pre> element
    const cssOutputs = screen.getAllByText(/background:/)
    const cssOutput = cssOutputs.find((el) => el.tagName === 'PRE')
    expect(cssOutput).toBeDefined()
    expect(cssOutput?.textContent).toContain('conic-gradient')
  })
})

describe('Gradient Generator - Presets', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should display preset categories', () => {
    renderPage()

    expect(screen.getByText('sunset')).toBeInTheDocument()
    expect(screen.getByText('ocean')).toBeInTheDocument()
    expect(screen.getByText('forest')).toBeInTheDocument()
    expect(screen.getByText('fire')).toBeInTheDocument()
    expect(screen.getByText('neon')).toBeInTheDocument()
    expect(screen.getByText('pastel')).toBeInTheDocument()
    expect(screen.getByText('special')).toBeInTheDocument()
  })

  it('should apply preset when clicked', async () => {
    renderPage()

    // Find all preset buttons (they have titles)
    const presetButtons = screen.getAllByRole('button').filter((btn) => btn.hasAttribute('title'))

    expect(presetButtons.length).toBeGreaterThan(0)

    // Click the first preset
    if (presetButtons[0]) {
      await userEvent.click(presetButtons[0])

      await waitFor(() => {
        expect(toast.success).toHaveBeenCalled()
      })
    }
  })
})

describe('Gradient Generator - Color Stop Management', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should update color stop color', () => {
    renderPage()

    const colorInputs = screen.getAllByRole('textbox')
    const firstInput = colorInputs[0]

    fireEvent.change(firstInput, { target: { value: '#ff0000' } })

    expect(firstInput).toHaveValue('#ff0000')
  })

  it('should update color stop position', () => {
    renderPage()

    // Find position sliders (range inputs)
    const sliders = document.querySelectorAll('input[type="range"]')
    const colorStopSlider = Array.from(sliders).find(
      (slider) =>
        slider.getAttribute('min') === '0' &&
        slider.getAttribute('max') === '100' &&
        !slider.closest('[data-angle-control]')
    )

    if (colorStopSlider) {
      fireEvent.change(colorStopSlider, { target: { value: '75' } })
      expect(colorStopSlider).toHaveValue('75')
    }
  })
})

describe('Gradient Generator - Angle Control', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should update angle for linear gradient', () => {
    renderPage()

    // Find angle slider
    const sliders = document.querySelectorAll('input[type="range"]')
    const angleSlider = Array.from(sliders).find(
      (slider) => slider.getAttribute('min') === '0' && slider.getAttribute('max') === '360'
    )

    if (angleSlider) {
      fireEvent.change(angleSlider, { target: { value: '180' } })
      expect(screen.getByText(/Angle: 180°/)).toBeInTheDocument()
    }
  })

  it('should show angle control for conic gradient', async () => {
    renderPage()

    const conicButton = screen.getByRole('button', { name: 'conic' })
    await userEvent.click(conicButton)

    expect(screen.getByText(/Angle:/)).toBeInTheDocument()
  })
})

describe('Gradient Generator - Accessibility', () => {
  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
      },
    })
    vi.clearAllMocks()
  })

  it('should have proper heading hierarchy', () => {
    renderPage()

    const h1 = screen.getByRole('heading', { level: 1 })
    const h2s = screen.getAllByRole('heading', { level: 2 })

    expect(h1).toBeInTheDocument()
    expect(h2s.length).toBeGreaterThanOrEqual(3) // Preview, Controls, Presets
  })

  it('should have accessible buttons', () => {
    renderPage()

    const buttons = screen.getAllByRole('button')
    buttons.forEach((button) => {
      // All buttons should be in the document and have some content
      expect(button).toBeInTheDocument()
    })
  })
})
