import { describe, it, expect } from 'vitest'

// Split Bill Calculator logic functions
interface Person {
  id: string
  name: string
  hasPaid: boolean
}

interface Calculations {
  bill: number
  tipAmount: number
  taxAmount: number
  total: number
  perPerson: number
  paidCount: number
  unpaidCount: number
  totalPaid: number
  totalUnpaid: number
}

function calculateBillSplit(
  billAmount: string,
  tipPercent: string,
  taxPercent: string,
  people: Person[]
): Calculations {
  const bill = parseFloat(billAmount) || 0
  const tip = parseFloat(tipPercent) || 0
  const tax = parseFloat(taxPercent) || 0
  const numPeople = people.length

  const tipAmount = (bill * tip) / 100
  const taxAmount = (bill * tax) / 100
  const total = bill + tipAmount + taxAmount
  const perPerson = numPeople > 0 ? total / numPeople : 0

  const paidCount = people.filter((p) => p.hasPaid).length
  const unpaidCount = numPeople - paidCount
  const totalPaid = paidCount * perPerson
  const totalUnpaid = unpaidCount * perPerson

  return {
    bill,
    tipAmount,
    taxAmount,
    total,
    perPerson,
    paidCount,
    unpaidCount,
    totalPaid,
    totalUnpaid,
  }
}

function generateSummary(
  calculations: Calculations,
  people: Person[],
  tipPercent: string,
  taxPercent: string,
  currencySymbol: string,
  currencyCode: string,
  currencyName: string,
  formatCurrency: (amount: number) => string
): string {
  const summary = `
💰 Bill Split Summary

📋 Bill Details:
- Subtotal: ${currencySymbol}${formatCurrency(calculations.bill)}
- Tip (${tipPercent}%): ${currencySymbol}${formatCurrency(calculations.tipAmount)}
- Tax (${taxPercent}%): ${currencySymbol}${formatCurrency(calculations.taxAmount)}
- Total: ${currencySymbol}${formatCurrency(calculations.total)}

👥 Split Among ${people.length} People:
${people.map((p) => `- ${p.name}: ${currencySymbol}${formatCurrency(calculations.perPerson)} ${p.hasPaid ? '✅ Paid' : '⏳ Pending'}`).join('\n')}

💵 Per Person: ${currencySymbol}${formatCurrency(calculations.perPerson)}
✅ Paid: ${calculations.paidCount} (${currencySymbol}${formatCurrency(calculations.totalPaid)})
⏳ Unpaid: ${calculations.unpaidCount} (${currencySymbol}${formatCurrency(calculations.totalUnpaid)})

Currency: ${currencyCode} (${currencyName})
Generated by SuperTool Split Bill Calculator
  `.trim()

  return summary
}

describe('Split Bill Calculator Logic', () => {
  describe('Basic Calculations', () => {
    it('calculates bill split for 2 people with no tip or tax', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '0', '0', people)

      expect(result.bill).toBe(100)
      expect(result.tipAmount).toBe(0)
      expect(result.taxAmount).toBe(0)
      expect(result.total).toBe(100)
      expect(result.perPerson).toBe(50)
      expect(result.paidCount).toBe(0)
      expect(result.unpaidCount).toBe(2)
    })

    it('calculates bill split with tip', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '15', '0', people)

      expect(result.bill).toBe(100)
      expect(result.tipAmount).toBe(15)
      expect(result.taxAmount).toBe(0)
      expect(result.total).toBe(115)
      expect(result.perPerson).toBe(57.5)
    })

    it('calculates bill split with tax', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '0', '10', people)

      expect(result.bill).toBe(100)
      expect(result.tipAmount).toBe(0)
      expect(result.taxAmount).toBe(10)
      expect(result.total).toBe(110)
      expect(result.perPerson).toBe(55)
    })

    it('calculates bill split with both tip and tax', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '15', '10', people)

      expect(result.bill).toBe(100)
      expect(result.tipAmount).toBe(15)
      expect(result.taxAmount).toBe(10)
      expect(result.total).toBe(125)
      expect(result.perPerson).toBe(62.5)
    })
  })

  describe('Multiple People', () => {
    it('calculates split for 3 people', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
        { id: '3', name: 'Person 3', hasPaid: false },
      ]

      const result = calculateBillSplit('150', '20', '10', people)

      expect(result.total).toBe(195) // 150 + 30 (tip) + 15 (tax)
      expect(result.perPerson).toBe(65)
      expect(result.unpaidCount).toBe(3)
    })

    it('calculates split for 5 people', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
        { id: '3', name: 'Person 3', hasPaid: false },
        { id: '4', name: 'Person 4', hasPaid: false },
        { id: '5', name: 'Person 5', hasPaid: false },
      ]

      const result = calculateBillSplit('200', '18', '8', people)

      expect(result.bill).toBe(200)
      expect(result.tipAmount).toBe(36)
      expect(result.taxAmount).toBe(16)
      expect(result.total).toBe(252)
      expect(result.perPerson).toBe(50.4)
    })
  })

  describe('Payment Tracking', () => {
    it('tracks paid and unpaid people', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: true },
        { id: '2', name: 'Person 2', hasPaid: false },
        { id: '3', name: 'Person 3', hasPaid: true },
      ]

      const result = calculateBillSplit('90', '10', '5', people)

      expect(result.paidCount).toBe(2)
      expect(result.unpaidCount).toBe(1)
      expect(result.perPerson).toBeCloseTo(34.5, 1) // 90 + 9 + 4.5 = 103.5 / 3
      expect(result.totalPaid).toBeCloseTo(69, 1) // 2 * 34.5
      expect(result.totalUnpaid).toBeCloseTo(34.5, 1) // 1 * 34.5
    })

    it('handles all people paid', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: true },
        { id: '2', name: 'Person 2', hasPaid: true },
      ]

      const result = calculateBillSplit('100', '15', '10', people)

      expect(result.paidCount).toBe(2)
      expect(result.unpaidCount).toBe(0)
      expect(result.totalUnpaid).toBe(0)
    })

    it('handles no people paid', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
        { id: '3', name: 'Person 3', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '15', '10', people)

      expect(result.paidCount).toBe(0)
      expect(result.unpaidCount).toBe(3)
      expect(result.totalPaid).toBe(0)
    })
  })

  describe('Edge Cases', () => {
    it('handles empty bill amount', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('', '15', '10', people)

      expect(result.bill).toBe(0)
      expect(result.tipAmount).toBe(0)
      expect(result.taxAmount).toBe(0)
      expect(result.total).toBe(0)
      expect(result.perPerson).toBe(0)
    })

    it('handles invalid bill amount', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('abc', '15', '10', people)

      expect(result.bill).toBe(0)
      expect(result.total).toBe(0)
    })

    it('handles negative values', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('-100', '-15', '-10', people)

      expect(result.bill).toBe(-100)
      expect(result.tipAmount).toBe(15) // -100 * -15 / 100
      expect(result.taxAmount).toBe(10) // -100 * -10 / 100
    })

    it('handles decimal amounts', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('99.99', '15.5', '8.25', people)

      expect(result.bill).toBeCloseTo(99.99, 2)
      expect(result.tipAmount).toBeCloseTo(15.49845, 2)
      expect(result.taxAmount).toBeCloseTo(8.249175, 2)
      expect(result.total).toBeCloseTo(123.737625, 2)
    })

    it('handles zero people', () => {
      const people: Person[] = []

      const result = calculateBillSplit('100', '15', '10', people)

      expect(result.total).toBe(125)
      expect(result.perPerson).toBe(0)
      expect(result.paidCount).toBe(0)
      expect(result.unpaidCount).toBe(0)
    })

    it('handles one person', () => {
      const people: Person[] = [{ id: '1', name: 'Solo', hasPaid: false }]

      const result = calculateBillSplit('100', '15', '10', people)

      expect(result.perPerson).toBe(125)
      expect(result.unpaidCount).toBe(1)
    })
  })

  describe('Large Numbers', () => {
    it('handles large bill amounts', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('10000', '20', '15', people)

      expect(result.bill).toBe(10000)
      expect(result.tipAmount).toBe(2000)
      expect(result.taxAmount).toBe(1500)
      expect(result.total).toBe(13500)
      expect(result.perPerson).toBe(6750)
    })

    it('handles many people', () => {
      const people: Person[] = Array.from({ length: 20 }, (_, i) => ({
        id: String(i + 1),
        name: `Person ${i + 1}`,
        hasPaid: false,
      }))

      const result = calculateBillSplit('1000', '15', '10', people)

      expect(result.total).toBe(1250)
      expect(result.perPerson).toBe(62.5)
      expect(result.unpaidCount).toBe(20)
    })
  })

  describe('Percentage Calculations', () => {
    it('calculates 0% tip', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '0', '10', people)

      expect(result.tipAmount).toBe(0)
    })

    it('calculates 100% tip', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '100', '0', people)

      expect(result.tipAmount).toBe(100)
      expect(result.total).toBe(200)
    })

    it('calculates fractional percentages', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const result = calculateBillSplit('100', '12.5', '7.75', people)

      expect(result.tipAmount).toBe(12.5)
      expect(result.taxAmount).toBe(7.75)
      expect(result.total).toBe(120.25)
    })
  })

  describe('Summary Generation', () => {
    const mockFormatCurrency = (amount: number) => amount.toFixed(2)

    it('generates summary with all details', () => {
      const people: Person[] = [
        { id: '1', name: 'Alice', hasPaid: true },
        { id: '2', name: 'Bob', hasPaid: false },
      ]

      const calculations = calculateBillSplit('100', '15', '10', people)
      const summary = generateSummary(
        calculations,
        people,
        '15',
        '10',
        '$',
        'USD',
        'US Dollar',
        mockFormatCurrency
      )

      expect(summary).toContain('Bill Split Summary')
      expect(summary).toContain('Subtotal: $100.00')
      expect(summary).toContain('Tip (15%): $15.00')
      expect(summary).toContain('Tax (10%): $10.00')
      expect(summary).toContain('Total: $125.00')
      expect(summary).toContain('Alice: $62.50 ✅ Paid')
      expect(summary).toContain('Bob: $62.50 ⏳ Pending')
      expect(summary).toContain('Currency: USD (US Dollar)')
    })

    it('generates summary with IDR currency', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: false },
        { id: '2', name: 'Person 2', hasPaid: false },
      ]

      const calculations = calculateBillSplit('100000', '15', '10', people)
      const mockFormatIDR = (amount: number) => {
        return new Intl.NumberFormat('id-ID', {
          minimumFractionDigits: 0,
          maximumFractionDigits: 0,
        }).format(amount)
      }

      const summary = generateSummary(
        calculations,
        people,
        '15',
        '10',
        'Rp',
        'IDR',
        'Indonesian Rupiah',
        mockFormatIDR
      )

      expect(summary).toContain('Subtotal: Rp100.000')
      expect(summary).toContain('Currency: IDR (Indonesian Rupiah)')
    })

    it('generates summary with multiple people', () => {
      const people: Person[] = [
        { id: '1', name: 'Alice', hasPaid: true },
        { id: '2', name: 'Bob', hasPaid: true },
        { id: '3', name: 'Charlie', hasPaid: false },
        { id: '4', name: 'Diana', hasPaid: false },
      ]

      const calculations = calculateBillSplit('200', '18', '8', people)
      const summary = generateSummary(
        calculations,
        people,
        '18',
        '8',
        '$',
        'USD',
        'US Dollar',
        mockFormatCurrency
      )

      expect(summary).toContain('Split Among 4 People')
      expect(summary).toContain('Alice')
      expect(summary).toContain('Bob')
      expect(summary).toContain('Charlie')
      expect(summary).toContain('Diana')
      expect(summary).toContain('Paid: 2')
      expect(summary).toContain('Unpaid: 2')
    })
  })

  describe('Real-world Scenarios', () => {
    it('handles restaurant bill with standard tip', () => {
      const people: Person[] = [
        { id: '1', name: 'Alice', hasPaid: true },
        { id: '2', name: 'Bob', hasPaid: true },
        { id: '3', name: 'Charlie', hasPaid: false },
        { id: '4', name: 'Diana', hasPaid: false },
      ]

      const result = calculateBillSplit('85.50', '18', '8.5', people)

      expect(result.bill).toBeCloseTo(85.5, 2)
      expect(result.tipAmount).toBeCloseTo(15.39, 2)
      expect(result.taxAmount).toBeCloseTo(7.2675, 2)
      expect(result.total).toBeCloseTo(108.1575, 2)
      expect(result.perPerson).toBeCloseTo(27.039375, 2)
      expect(result.paidCount).toBe(2)
      expect(result.unpaidCount).toBe(2)
    })

    it('handles Indonesian restaurant bill', () => {
      const people: Person[] = [
        { id: '1', name: 'Budi', hasPaid: false },
        { id: '2', name: 'Siti', hasPaid: false },
        { id: '3', name: 'Andi', hasPaid: false },
      ]

      const result = calculateBillSplit('450000', '10', '10', people)

      expect(result.bill).toBe(450000)
      expect(result.tipAmount).toBe(45000)
      expect(result.taxAmount).toBe(45000)
      expect(result.total).toBe(540000)
      expect(result.perPerson).toBe(180000)
    })

    it('handles bar tab with high tip', () => {
      const people: Person[] = [
        { id: '1', name: 'Person 1', hasPaid: true },
        { id: '2', name: 'Person 2', hasPaid: true },
      ]

      const result = calculateBillSplit('120', '25', '7', people)

      expect(result.bill).toBe(120)
      expect(result.tipAmount).toBe(30)
      expect(result.taxAmount).toBe(8.4)
      expect(result.total).toBe(158.4)
      expect(result.perPerson).toBe(79.2)
      expect(result.paidCount).toBe(2)
    })
  })
})
