import type { Metadata } from 'next'
import Script from 'next/script'
import { generateToolBreadcrumbs, generateToolMetadata } from '@/lib/metadata'
import { generateBreadcrumbSchema, generateFAQSchema } from '@/lib/structured-data'

export const metadata: Metadata = generateToolMetadata({
  title: 'Secure Password Generator',
  description:
    'Generate strong, random passwords with customizable length and character types. Create secure passwords with uppercase, lowercase, numbers, and special characters. Privacy-focused with instant generation.',
  keywords: [
    'password generator',
    'random password',
    'strong password',
    'secure password',
    'password maker',
    'password creator',
    'generate password',
    'random password generator',
    'secure password generator',
    'password strength',
    'passphrase generator',
    'complex password',
  ],
  category: 'security',
  path: '/tools/password-generator',
})

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://supertool.id'
const breadcrumbs = generateToolBreadcrumbs('Secure Password Generator')

const faqs = [
  {
    question: 'How secure are the passwords generated by this tool?',
    answer:
      'Our password generator uses cryptographically secure random number generation (Web Crypto API) to create truly random passwords. The generation happens entirely in your browser, so passwords are never transmitted over the internet or stored anywhere.',
  },
  {
    question: 'What makes a strong password?',
    answer:
      'A strong password should be at least 12 characters long and include a mix of uppercase letters, lowercase letters, numbers, and special characters. The longer and more varied the password, the harder it is to crack. Our generator follows these best practices by default.',
  },
  {
    question: 'How long should my password be?',
    answer:
      'We recommend passwords of at least 12-16 characters for most accounts. For highly sensitive accounts like banking or email, consider 20+ characters. Our generator supports passwords up to 128 characters for maximum security.',
  },
  {
    question: 'Should I use different passwords for different accounts?',
    answer:
      'Yes, absolutely! Using unique passwords for each account is crucial. If one account is compromised, others remain secure. Our bulk generation feature makes it easy to create multiple unique passwords at once. Consider using a password manager to store them securely.',
  },
]

export default function PasswordGeneratorLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe usage for JSON-LD structured data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(generateBreadcrumbSchema(breadcrumbs, baseUrl)),
        }}
      />
      <Script
        id="faq-schema"
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe usage for JSON-LD structured data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(generateFAQSchema(faqs)),
        }}
      />
    </>
  )
}
