/**
 * Export utilities for Split Bill Calculator
 * Provides PDF, CSV, and image export functionality
 */

import type { Currency } from './currency'

interface ExportData {
  title?: string
  billAmount: number
  tipAmount: number
  tipPercent: string
  taxAmount: number
  taxPercent: string
  total: number
  currency: Currency
  people: Array<{
    name: string
    amount: number
    hasPaid: boolean
    percentage?: number
  }>
  splitType: 'equal' | 'percentage' | 'items'
  items?: Array<{
    name: string
    price: number
    quantity: number
    assignedTo: string[]
  }>
  createdAt?: string
}

/**
 * Export bill data as CSV
 */
export function exportToCSV(data: ExportData): string {
  const rows: string[][] = []

  // Header
  rows.push(['Split Bill Summary'])
  rows.push([])

  // Bill details
  rows.push(['Bill Details'])
  rows.push(['Subtotal', data.currency.symbol + data.billAmount.toFixed(2)])
  rows.push([`Tip (${data.tipPercent}%)`, data.currency.symbol + data.tipAmount.toFixed(2)])
  rows.push([`Tax (${data.taxPercent}%)`, data.currency.symbol + data.taxAmount.toFixed(2)])
  rows.push(['Total', data.currency.symbol + data.total.toFixed(2)])
  rows.push([])

  // People
  rows.push([
    'Participants',
    'Amount',
    'Status',
    data.splitType === 'percentage' ? 'Percentage' : '',
  ])
  data.people.forEach((person) => {
    const percentageCol = data.splitType === 'percentage' ? `${person.percentage?.toFixed(1)}%` : ''
    rows.push([
      person.name,
      data.currency.symbol + person.amount.toFixed(2),
      person.hasPaid ? 'Paid' : 'Pending',
      percentageCol,
    ])
  })
  rows.push([])

  // Items (if item-based split)
  if (data.splitType === 'items' && data.items && data.items.length > 0) {
    rows.push(['Items', 'Price', 'Quantity', 'Total', 'Assigned To'])
    data.items.forEach((item) => {
      const assignedNames = item.assignedTo
        .map((id) => data.people.find((p) => p.name === id)?.name)
        .filter(Boolean)
        .join(', ')
      rows.push([
        item.name,
        data.currency.symbol + item.price.toFixed(2),
        item.quantity.toString(),
        data.currency.symbol + (item.price * item.quantity).toFixed(2),
        assignedNames,
      ])
    })
    rows.push([])
  }

  // Summary stats
  const paidCount = data.people.filter((p) => p.hasPaid).length
  const unpaidCount = data.people.length - paidCount
  rows.push(['Summary'])
  rows.push(['Total Participants', data.people.length.toString()])
  rows.push(['Paid', paidCount.toString()])
  rows.push(['Unpaid', unpaidCount.toString()])
  rows.push([])

  // Metadata
  if (data.createdAt) {
    rows.push(['Created', new Date(data.createdAt).toLocaleString()])
  }
  rows.push(['Currency', `${data.currency.code} (${data.currency.name})`])
  rows.push(['Generated by', 'SuperTool Split Bill Calculator'])

  // Convert to CSV string
  return rows.map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')
}

/**
 * Download CSV file
 */
export function downloadCSV(data: ExportData, filename?: string): void {
  const csv = exportToCSV(data)
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)

  link.setAttribute('href', url)
  link.setAttribute(
    'download',
    filename || `split-bill-${new Date().toISOString().split('T')[0]}.csv`
  )
  link.style.visibility = 'hidden'

  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

/**
 * Export bill as formatted text (for messaging apps)
 */
export function exportAsText(data: ExportData): string {
  const splitTypeText =
    data.splitType === 'percentage'
      ? 'Custom Percentage'
      : data.splitType === 'items'
        ? 'Item-Based'
        : 'Equal Split'

  let text = `💰 Bill Split Summary\n\n`

  if (data.title) {
    text += `📋 ${data.title}\n\n`
  }

  text += `📋 Bill Details:\n`
  text += `- Subtotal: ${data.currency.symbol}${data.billAmount.toFixed(2)}\n`
  text += `- Tip (${data.tipPercent}%): ${data.currency.symbol}${data.tipAmount.toFixed(2)}\n`
  text += `- Tax (${data.taxPercent}%): ${data.currency.symbol}${data.taxAmount.toFixed(2)}\n`
  text += `- Total: ${data.currency.symbol}${data.total.toFixed(2)}\n\n`

  text += `👥 Split Among ${data.people.length} People (${splitTypeText}):\n`
  data.people.forEach((person) => {
    const percentageText =
      data.splitType === 'percentage' ? ` (${person.percentage?.toFixed(1)}%)` : ''
    const status = person.hasPaid ? '✅ Paid' : '⏳ Pending'
    text += `- ${person.name}: ${data.currency.symbol}${person.amount.toFixed(
      2
    )}${percentageText} ${status}\n`
  })

  const paidCount = data.people.filter((p) => p.hasPaid).length
  const unpaidCount = data.people.length - paidCount
  const totalPaid = data.people.filter((p) => p.hasPaid).reduce((sum, p) => sum + p.amount, 0)
  const totalUnpaid = data.people.filter((p) => !p.hasPaid).reduce((sum, p) => sum + p.amount, 0)

  text += `\n💵 Per Person (Average): ${data.currency.symbol}${(
    data.total / data.people.length
  ).toFixed(2)}\n`
  text += `✅ Paid: ${paidCount} (${data.currency.symbol}${totalPaid.toFixed(2)})\n`
  text += `⏳ Unpaid: ${unpaidCount} (${data.currency.symbol}${totalUnpaid.toFixed(2)})\n\n`

  text += `Currency: ${data.currency.code} (${data.currency.name})\n`
  text += `Generated by SuperTool Split Bill Calculator`

  return text
}

/**
 * Generate payment request text for a specific person
 */
export function generatePaymentRequest(
  personName: string,
  amount: number,
  currency: Currency,
  organizerName?: string,
  bankAccount?: string,
  bankName?: string
): string {
  let text = `💰 Payment Request\n\n`
  text += `Hi ${personName}! 👋\n\n`
  text += `Your share of the bill is: ${currency.symbol}${amount.toFixed(2)}\n\n`

  if (organizerName) {
    text += `Please send payment to: ${organizerName}\n`
  }

  if (bankAccount && bankName) {
    text += `\n📱 Payment Details:\n`
    text += `Bank: ${bankName}\n`
    text += `Account: ${bankAccount}\n`
  }

  text += `\nThank you! 😊`

  return text
}

/**
 * Generate deep link for payment apps
 */
export function generatePaymentLink(
  app: 'venmo' | 'paypal' | 'cashapp',
  amount: number,
  recipient: string,
  note?: string
): string {
  const encodedNote = encodeURIComponent(note || 'Bill split payment')

  switch (app) {
    case 'venmo':
      // Venmo deep link format: venmo://paycharge?txn=pay&recipients=USERNAME&amount=100&note=Bill
      return `venmo://paycharge?txn=pay&recipients=${recipient}&amount=${amount}&note=${encodedNote}`

    case 'paypal':
      // PayPal.Me link format
      return `https://paypal.me/${recipient}/${amount}`

    case 'cashapp':
      // Cash App deep link format: https://cash.app/$USERNAME/100
      return `https://cash.app/$${recipient}/${amount}`

    default:
      return ''
  }
}

/**
 * Copy to clipboard utility
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof window === 'undefined') return false

  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch (error) {
    console.error('Failed to copy to clipboard:', error)
    return false
  }
}
