/**
 * @vitest-environment jsdom
 */
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { Currency } from '../currency'
import {
  copyToClipboard,
  downloadCSV,
  exportAsText,
  exportToCSV,
  generatePaymentLink,
  generatePaymentRequest,
} from '../split-bill-export-legacy'

describe('split-bill-export-legacy', () => {
  let mockCurrency: Currency
  let mockData: any

  beforeEach(() => {
    mockCurrency = {
      code: 'USD',
      symbol: '$',
      name: 'US Dollar',
      iconName: 'DollarSign',
    }

    mockData = {
      title: 'Team Lunch',
      billAmount: 100,
      tipAmount: 15,
      tipPercent: '15',
      taxAmount: 8.5,
      taxPercent: '8.5',
      total: 123.5,
      currency: mockCurrency,
      people: [
        { name: 'Alice', amount: 41.17, hasPaid: true, percentage: 33.3 },
        { name: 'Bob', amount: 41.17, hasPaid: false, percentage: 33.3 },
        { name: 'Charlie', amount: 41.16, hasPaid: false, percentage: 33.4 },
      ],
      splitType: 'equal' as const,
      items: [
        { name: 'Pizza', price: 15, quantity: 2, assignedTo: ['Alice', 'Bob'] },
        { name: 'Salad', price: 10, quantity: 3, assignedTo: ['Charlie'] },
      ],
      createdAt: '2024-01-15T12:00:00Z',
    }
  })

  describe('exportToCSV', () => {
    it('should export equal split data to CSV format', () => {
      const csv = exportToCSV(mockData)

      expect(csv).toContain('Split Bill Summary')
      expect(csv).toContain('Bill Details')
      expect(csv).toContain('$100.00')
      expect(csv).toContain('Tip (15%)')
      expect(csv).toContain('$15.00')
      expect(csv).toContain('Tax (8.5%)')
      expect(csv).toContain('$8.50')
      expect(csv).toContain('Total')
      expect(csv).toContain('$123.50')
    })

    it('should include participant information', () => {
      const csv = exportToCSV(mockData)

      expect(csv).toContain('Participants')
      expect(csv).toContain('Alice')
      expect(csv).toContain('$41.17')
      expect(csv).toContain('Paid')
      expect(csv).toContain('Bob')
      expect(csv).toContain('Pending')
      expect(csv).toContain('Charlie')
    })

    it('should include percentage column for percentage split', () => {
      const percentageData = { ...mockData, splitType: 'percentage' as const }
      const csv = exportToCSV(percentageData)

      expect(csv).toContain('Percentage')
      expect(csv).toContain('33.3%')
      expect(csv).toContain('33.4%')
    })

    it('should not include percentage column for equal split', () => {
      const csv = exportToCSV(mockData)

      expect(csv).not.toContain('33.3%')
    })

    it('should include items section for item-based split', () => {
      const itemData = { ...mockData, splitType: 'items' as const }
      const csv = exportToCSV(itemData)

      expect(csv).toContain('Items')
      expect(csv).toContain('Pizza')
      expect(csv).toContain('$15.00')
      expect(csv).toContain('2')
      expect(csv).toContain('$30.00')
      expect(csv).toContain('Alice, Bob')
      expect(csv).toContain('Salad')
      expect(csv).toContain('$10.00')
      expect(csv).toContain('3')
      expect(csv).toContain('Charlie')
    })

    it('should not include items section when items array is empty', () => {
      const itemData = { ...mockData, splitType: 'items' as const, items: [] }
      const csv = exportToCSV(itemData)

      expect(csv).not.toContain('Items')
      expect(csv).not.toContain('Pizza')
    })

    it('should not include items section for non-item split types', () => {
      const csv = exportToCSV(mockData)

      expect(csv).not.toContain('Quantity')
      expect(csv).not.toContain('Pizza')
    })

    it('should include summary statistics', () => {
      const csv = exportToCSV(mockData)

      expect(csv).toContain('Summary')
      expect(csv).toContain('Total Participants')
      expect(csv).toContain('"3"')
      expect(csv).toContain('Paid')
      expect(csv).toContain('"1"')
      expect(csv).toContain('Unpaid')
      expect(csv).toContain('"2"')
    })

    it('should include metadata', () => {
      const csv = exportToCSV(mockData)

      expect(csv).toContain('Currency')
      expect(csv).toContain('USD')
      expect(csv).toContain('US Dollar')
      expect(csv).toContain('Generated by')
      expect(csv).toContain('SuperTool Split Bill Calculator')
    })

    it('should include createdAt date when provided', () => {
      const csv = exportToCSV(mockData)

      expect(csv).toContain('Created')
    })

    it('should handle missing createdAt date', () => {
      const dataWithoutDate = { ...mockData, createdAt: undefined }
      const csv = exportToCSV(dataWithoutDate)

      expect(csv).not.toContain('Created')
      expect(csv).toContain('Currency')
    })

    it('should properly escape CSV values with quotes', () => {
      const csv = exportToCSV(mockData)

      // CSV should wrap all cells in quotes
      expect(csv).toMatch(/"[^"]+"/g)
    })

    it('should handle different currencies', () => {
      const euroData = {
        ...mockData,
        currency: { ...mockCurrency, code: 'EUR', symbol: '€', name: 'Euro' },
      }
      const csv = exportToCSV(euroData)

      expect(csv).toContain('€')
      expect(csv).toContain('EUR')
      expect(csv).toContain('Euro')
    })
  })

  describe('downloadCSV', () => {
    beforeEach(() => {
      // Mock DOM APIs
      global.URL.createObjectURL = vi.fn(() => 'blob:mock-url')
      global.URL.revokeObjectURL = vi.fn()

      // Mock document methods
      const mockLink = {
        setAttribute: vi.fn(),
        click: vi.fn(),
        style: {},
      }
      vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any)
      vi.spyOn(document.body, 'appendChild').mockImplementation(() => mockLink as any)
      vi.spyOn(document.body, 'removeChild').mockImplementation(() => mockLink as any)
    })

    it('should create and download CSV file', () => {
      downloadCSV(mockData)

      expect(document.createElement).toHaveBeenCalledWith('a')
      expect(global.URL.createObjectURL).toHaveBeenCalledWith(expect.any(Blob))
    })

    it('should use default filename when not provided', () => {
      const mockLink = {
        setAttribute: vi.fn(),
        click: vi.fn(),
        style: {},
      }
      vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any)

      downloadCSV(mockData)

      const setAttributeCalls = mockLink.setAttribute.mock.calls
      const downloadCall = setAttributeCalls.find((call) => call[0] === 'download')
      expect(downloadCall).toBeDefined()
      expect(downloadCall?.[1]).toMatch(/split-bill-\d{4}-\d{2}-\d{2}\.csv/)
    })

    it('should use custom filename when provided', () => {
      const mockLink = {
        setAttribute: vi.fn(),
        click: vi.fn(),
        style: {},
      }
      vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any)

      downloadCSV(mockData, 'custom-bill.csv')

      const setAttributeCalls = mockLink.setAttribute.mock.calls
      const downloadCall = setAttributeCalls.find((call) => call[0] === 'download')
      expect(downloadCall?.[1]).toBe('custom-bill.csv')
    })

    it('should trigger download click', () => {
      const mockLink = {
        setAttribute: vi.fn(),
        click: vi.fn(),
        style: {},
      }
      vi.spyOn(document, 'createElement').mockReturnValue(mockLink as any)

      downloadCSV(mockData)

      expect(mockLink.click).toHaveBeenCalledTimes(1)
    })

    it('should add and remove link from DOM', () => {
      downloadCSV(mockData)

      expect(document.body.appendChild).toHaveBeenCalled()
      expect(document.body.removeChild).toHaveBeenCalled()
    })
  })

  describe('exportAsText', () => {
    it('should generate formatted text for messaging', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('💰 Bill Split Summary')
      expect(text).toContain('📋 Bill Details:')
      expect(text).toContain('👥 Split Among')
      expect(text).toContain('$100.00')
      expect(text).toContain('$15.00')
      expect(text).toContain('$8.50')
      expect(text).toContain('$123.50')
    })

    it('should include title when provided', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('📋 Team Lunch')
    })

    it('should not include title section when not provided', () => {
      const dataWithoutTitle = { ...mockData, title: undefined }
      const text = exportAsText(dataWithoutTitle)

      expect(text).not.toContain('📋 Team')
      expect(text).toContain('📋 Bill Details')
    })

    it('should show equal split type', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('Equal Split')
    })

    it('should show percentage split type', () => {
      const percentageData = { ...mockData, splitType: 'percentage' as const }
      const text = exportAsText(percentageData)

      expect(text).toContain('Custom Percentage')
      expect(text).toContain('33.3%')
    })

    it('should show item-based split type', () => {
      const itemData = { ...mockData, splitType: 'items' as const }
      const text = exportAsText(itemData)

      expect(text).toContain('Item-Based')
    })

    it('should include participant details with status', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('Alice')
      expect(text).toContain('$41.17')
      expect(text).toContain('✅ Paid')
      expect(text).toContain('Bob')
      expect(text).toContain('⏳ Pending')
      expect(text).toContain('Charlie')
    })

    it('should calculate and show average per person', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('💵 Per Person (Average)')
      expect(text).toContain('$41.17')
    })

    it('should show paid/unpaid summary', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('✅ Paid: 1')
      expect(text).toContain('$41.17')
      expect(text).toContain('⏳ Unpaid: 2')
      expect(text).toContain('$82.33')
    })

    it('should include currency information', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('Currency: USD (US Dollar)')
    })

    it('should include attribution', () => {
      const text = exportAsText(mockData)

      expect(text).toContain('Generated by SuperTool Split Bill Calculator')
    })

    it('should handle all people paid', () => {
      const allPaidData = {
        ...mockData,
        people: mockData.people.map((p: any) => ({ ...p, hasPaid: true })),
      }
      const text = exportAsText(allPaidData)

      expect(text).toContain('✅ Paid: 3')
      expect(text).toContain('⏳ Unpaid: 0')
      expect(text).toContain('$0.00')
    })

    it('should handle no people paid', () => {
      const noPaidData = {
        ...mockData,
        people: mockData.people.map((p: any) => ({ ...p, hasPaid: false })),
      }
      const text = exportAsText(noPaidData)

      expect(text).toContain('✅ Paid: 0')
      expect(text).toContain('$0.00')
      expect(text).toContain('⏳ Unpaid: 3')
      expect(text).toContain('$123.50')
    })
  })

  describe('generatePaymentRequest', () => {
    it('should generate basic payment request', () => {
      const text = generatePaymentRequest('Alice', 50.0, mockCurrency)

      expect(text).toContain('💰 Payment Request')
      expect(text).toContain('Hi Alice! 👋')
      expect(text).toContain('Your share of the bill is: $50.00')
      expect(text).toContain('Thank you! 😊')
    })

    it('should include organizer name when provided', () => {
      const text = generatePaymentRequest('Bob', 30.0, mockCurrency, 'Charlie')

      expect(text).toContain('Please send payment to: Charlie')
    })

    it('should not include organizer section when not provided', () => {
      const text = generatePaymentRequest('Bob', 30.0, mockCurrency)

      expect(text).not.toContain('Please send payment to:')
    })

    it('should include bank details when provided', () => {
      const text = generatePaymentRequest('Alice', 50.0, mockCurrency, 'Bob', '1234567890', 'Chase')

      expect(text).toContain('📱 Payment Details:')
      expect(text).toContain('Bank: Chase')
      expect(text).toContain('Account: 1234567890')
    })

    it('should not include bank details when only account provided', () => {
      const text = generatePaymentRequest('Alice', 50.0, mockCurrency, 'Bob', '1234567890')

      expect(text).not.toContain('📱 Payment Details:')
      expect(text).not.toContain('Bank:')
    })

    it('should not include bank details when only bank name provided', () => {
      const text = generatePaymentRequest('Alice', 50.0, mockCurrency, 'Bob', undefined, 'Chase')

      expect(text).not.toContain('📱 Payment Details:')
      expect(text).not.toContain('Account:')
    })

    it('should format amount with currency symbol', () => {
      const euroC: Currency = { ...mockCurrency, symbol: '€', code: 'EUR' }
      const text = generatePaymentRequest('Alice', 75.5, euroC)

      expect(text).toContain('€75.50')
    })
  })

  describe('generatePaymentLink', () => {
    it('should generate Venmo deep link', () => {
      const link = generatePaymentLink('venmo', 50, 'alice123', 'Dinner split')

      expect(link).toBe(
        'venmo://paycharge?txn=pay&recipients=alice123&amount=50&note=Dinner%20split'
      )
    })

    it('should generate Venmo link with default note', () => {
      const link = generatePaymentLink('venmo', 50, 'alice123')

      expect(link).toContain('venmo://paycharge')
      expect(link).toContain('recipients=alice123')
      expect(link).toContain('amount=50')
      expect(link).toContain('note=Bill%20split%20payment')
    })

    it('should generate PayPal.Me link', () => {
      const link = generatePaymentLink('paypal', 50, 'alice123', 'Dinner split')

      expect(link).toBe('https://paypal.me/alice123/50')
    })

    it('should generate PayPal link without note (not supported)', () => {
      const link = generatePaymentLink('paypal', 75.5, 'bob456')

      expect(link).toBe('https://paypal.me/bob456/75.5')
      expect(link).not.toContain('note')
    })

    it('should generate Cash App link', () => {
      const link = generatePaymentLink('cashapp', 50, 'alice123', 'Dinner split')

      expect(link).toBe('https://cash.app/$alice123/50')
    })

    it('should generate Cash App link without note (not supported)', () => {
      const link = generatePaymentLink('cashapp', 100, 'charlie789')

      expect(link).toBe('https://cash.app/$charlie789/100')
      expect(link).not.toContain('note')
    })

    it('should handle special characters in note', () => {
      const link = generatePaymentLink('venmo', 50, 'alice', 'Team lunch @ café ☕')

      expect(link).toContain('Team%20lunch%20%40%20caf%C3%A9%20%E2%98%95')
    })

    it('should return empty string for unknown payment app', () => {
      const link = generatePaymentLink('unknown' as any, 50, 'alice')

      expect(link).toBe('')
    })
  })

  describe('copyToClipboard', () => {
    it('should copy text to clipboard successfully', async () => {
      const mockWriteText = vi.fn().mockResolvedValue(undefined)
      Object.defineProperty(navigator, 'clipboard', {
        writable: true,
        value: { writeText: mockWriteText },
      })

      const result = await copyToClipboard('Hello World')

      expect(result).toBe(true)
      expect(mockWriteText).toHaveBeenCalledWith('Hello World')
    })

    it('should return false when clipboard API fails', async () => {
      const mockWriteText = vi.fn().mockRejectedValue(new Error('Permission denied'))
      Object.defineProperty(navigator, 'clipboard', {
        writable: true,
        value: { writeText: mockWriteText },
      })

      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {})

      const result = await copyToClipboard('Hello World')

      expect(result).toBe(false)
      expect(consoleSpy).toHaveBeenCalledWith('Failed to copy to clipboard:', expect.any(Error))

      consoleSpy.mockRestore()
    })

    it('should return false in server-side environment', async () => {
      const originalWindow = global.window
      // @ts-expect-error - testing undefined window
      delete global.window

      const result = await copyToClipboard('Hello World')

      expect(result).toBe(false)

      // Restore window
      global.window = originalWindow
    })

    it('should handle empty string', async () => {
      const mockWriteText = vi.fn().mockResolvedValue(undefined)
      Object.defineProperty(navigator, 'clipboard', {
        writable: true,
        value: { writeText: mockWriteText },
      })

      const result = await copyToClipboard('')

      expect(result).toBe(true)
      expect(mockWriteText).toHaveBeenCalledWith('')
    })

    it('should handle long text', async () => {
      const mockWriteText = vi.fn().mockResolvedValue(undefined)
      Object.defineProperty(navigator, 'clipboard', {
        writable: true,
        value: { writeText: mockWriteText },
      })

      const longText = 'A'.repeat(10000)
      const result = await copyToClipboard(longText)

      expect(result).toBe(true)
      expect(mockWriteText).toHaveBeenCalledWith(longText)
    })
  })
})
