// Password generation and strength calculation utilities
import type { ZXCVBNResult } from 'zxcvbn'
import zxcvbnImport from 'zxcvbn'

const zxcvbn = zxcvbnImport as (password: string, userInputs?: string[]) => ZXCVBNResult

interface PasswordOptions {
  length: number
  uppercase: boolean
  lowercase: boolean
  numbers: boolean
  symbols: boolean
}

interface StrengthResult {
  score: number // 0-4 from zxcvbn
  label: string // Weak, Fair, Good, Strong, Very Strong
  color: string // Tailwind color
  feedback: string[] // Suggestions from zxcvbn
  entropy?: number // Bits of entropy
  crackTime?: string // Human-readable crack time
  crackTimeSeconds?: number // Crack time in seconds
}

export interface PasswordPattern {
  type: 'random' | 'diceware' | 'pronounceable' | 'template'
  name: string
  description: string
  template?: string
}

export interface PasswordHistory {
  password: string
  timestamp: number
  strength: StrengthResult
  favorite: boolean
  length: number
}

export interface PasswordTemplate {
  id: string
  name: string
  description: string
  pattern: string
  example: string
  category: 'banking' | 'social' | 'wifi' | 'email' | 'custom'
}

// Character sets for password generation
const CHAR_SETS = {
  uppercase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  lowercase: 'abcdefghijklmnopqrstuvwxyz',
  numbers: '0123456789',
  symbols: '!@#$%^&*()_+-=[]{}|;:,.<>?',
}

// Diceware word list (EFF long wordlist - subset for brevity)
const DICEWARE_WORDS = [
  'abacus',
  'abdomen',
  'abdominal',
  'abide',
  'abiding',
  'ability',
  'ablaze',
  'able',
  'abnormal',
  'abrasion',
  'abrasive',
  'abreast',
  'abridge',
  'abroad',
  'abruptly',
  'absence',
  'absentee',
  'absently',
  'absinthe',
  'absolute',
  'absolve',
  'abstain',
  'abstract',
  'absurd',
  'accent',
  'acclaim',
  'acclimate',
  'accompany',
  'account',
  'accuracy',
  'accurate',
  'accustom',
  'acetone',
  'achiness',
  'aching',
  'acid',
  'acorn',
  'acoustic',
  'acquaint',
  'acquire',
  'acre',
  'acrobat',
  'acronym',
  'acting',
  'action',
  'activate',
  'activator',
  'active',
  'activism',
  'activist',
  'activity',
  'actor',
  'actress',
  'actual',
  'actuator',
  'acutely',
  'acuteness',
  'aeration',
  'aerobics',
  'aerosol',
  'aerospace',
  'afar',
  'affair',
  'affected',
  'affecting',
  'affection',
  'affidavit',
  'affiliate',
  'affirm',
  'affix',
  'afflicted',
  'affluent',
  'afford',
  'affront',
  'aflame',
  'afloat',
  'aflutter',
  'afoot',
  'afraid',
  'afterglow',
  'afterlife',
  'aftermath',
  'aftermost',
  'afternoon',
  'agave',
  'aged',
  'ageless',
  'agency',
  'agenda',
  'agent',
  'aggregate',
  'aghast',
  'agile',
  'agility',
  'aging',
  'agnostic',
  'agonize',
  'agonizing',
  'agony',
  'agreeable',
  'agreeably',
  'agreed',
  'agreeing',
  'agreement',
  'aground',
  'ahead',
  'ahoy',
  'aide',
  'aids',
  'aim',
  'ajar',
  'alabaster',
  'alarm',
  'albatross',
  'album',
  'alfalfa',
  'algebra',
  'algorithm',
  'alibi',
  'alienable',
  'alienate',
  'aliens',
  'alike',
  'alive',
  'alkaline',
  'alkalize',
  'almanac',
  'almighty',
  'almost',
  'aloe',
  'aloft',
  'aloha',
  'alone',
  'alongside',
  'aloof',
  'alphabet',
  'alpine',
  'already',
  'also',
  'alter',
  'although',
  'altitude',
  'alto',
  'aluminum',
  'alumni',
  'always',
  'amaretto',
  'amaze',
  'amazingly',
  'amber',
  'ambiance',
  'ambiguity',
  'ambiguous',
  'ambition',
  'ambitious',
  'ambulance',
  'ambush',
  'amendable',
  'amendment',
  'amends',
  'amenity',
  'amiable',
  'amicably',
  'amid',
  'amigo',
  'amino',
  'amiss',
  'ammonia',
  'ammonium',
  'amnesty',
  'amniotic',
  'among',
  'amount',
  'amperage',
  'ampersand',
  'amphibian',
  'amphitheater',
  'ample',
  'amplifier',
  'amplify',
  'amply',
  'amuck',
  'amulet',
  'amusable',
  'amused',
  'amusement',
  'amuser',
  'amusing',
  'anaconda',
  'anaerobic',
  'anagram',
  'anatomist',
  'anatomy',
  'anchor',
  'anchovy',
  'ancient',
  'android',
  'anemia',
  'anemic',
  'aneurism',
  'anew',
  'angelfish',
  'angelic',
  'anger',
  'angled',
  'angler',
  'angles',
  'angling',
  'angrily',
  'angriness',
  'anguished',
  'angular',
  'animal',
  'animate',
  'animating',
  'animation',
  'animator',
  'anime',
  'animosity',
  'ankle',
  'annex',
  'annotate',
  'announcer',
  'annoying',
  'annually',
  'annuity',
  'anointer',
  'another',
  'answering',
  'antacid',
  'antarctic',
  'anteater',
  'antelope',
  'antennae',
  'anthem',
  'anthill',
  'anthology',
  'antibody',
  'antics',
  'antidote',
  'antihero',
  'antiquely',
  'antiques',
  'antiquity',
  'antirust',
  'antitoxic',
  'antitrust',
  'antiviral',
  'antivirus',
  'antler',
  'antonym',
  'antsy',
  'anvil',
  'anybody',
  'anyhow',
  'anymore',
  'anyone',
  'anyplace',
  'anything',
  'anytime',
  'anyway',
  'anywhere',
  'aorta',
  'apache',
  'apostle',
  'appealing',
  'appear',
  'appease',
  'appeasing',
  'appendage',
  'appendix',
  'appetite',
  'appetizer',
  'applaud',
  'applause',
  'apple',
  'appliance',
  'applicant',
  'applied',
  'apply',
  'appointee',
  'appraisal',
  'appraiser',
  'apprehend',
  'approach',
  'approval',
  'approve',
  'apricot',
  'april',
  'apron',
  'aptitude',
  'aptly',
  'aqua',
  'aqueduct',
  'arbitrary',
  'arbitrate',
  'ardently',
  'area',
  'arena',
  'arguable',
  'arguably',
  'argue',
  'arise',
  'armadillo',
  'armband',
  'armchair',
  'armed',
  'armful',
  'armhole',
  'arming',
  'armless',
  'armoire',
  'armored',
  'armory',
  'armrest',
  'army',
  'aroma',
  'arose',
  'around',
  'arousal',
  'arrange',
  'array',
  'arrest',
  'arrival',
  'arrive',
  'arrogance',
  'arrogant',
  'arson',
  'art',
  'ascend',
  'ascension',
  'ascent',
  'ascertain',
  'ashamed',
  'ashen',
  'ashes',
  'ashy',
  'aside',
  'askew',
  'asleep',
  'asparagus',
  'aspect',
  'aspirate',
  'aspire',
  'aspirin',
  'astonish',
  'astound',
  'astride',
  'astrology',
  'astronaut',
  'astronomy',
  'astute',
  'atlantic',
  'atlas',
  'atom',
  'atonable',
  'atop',
  'atrium',
  'atrocious',
  'atrophy',
  'attach',
  'attain',
  'attempt',
  'attendant',
  'attendee',
  'attention',
  'attentive',
  'attest',
  'attic',
  'attire',
  'attitude',
  'attractor',
  'attribute',
  'atypical',
  'auction',
  'audacious',
  'audacity',
  'audible',
  'audibly',
  'audience',
  'audio',
  'audition',
  'augmented',
  'august',
  'aunt',
  'authentic',
  'author',
  'autism',
  'autistic',
  'autograph',
  'automaker',
  'automated',
  'automatic',
  'autopilot',
  'available',
  'avalanche',
  'avatar',
  'avenge',
  'avenging',
  'avenue',
  'average',
  'aversion',
  'avert',
  'aviation',
  'aviator',
  'avid',
  'avoid',
  'await',
  'awaken',
  'award',
  'aware',
  'awhile',
  'awkward',
  'awning',
  'awoke',
  'awry',
  'axis',
  'babble',
  'babbling',
  'babied',
  'baboon',
  'backache',
  'backboard',
  'backbone',
  'backdate',
  'backdrop',
  'backed',
  'backer',
  'backfield',
  'backfire',
  'backhand',
  'backing',
  'backlands',
  'backlash',
  'backless',
  'backlight',
  'backlit',
  'backlog',
  'backpack',
  'backpedal',
  'backrest',
  'backroom',
  'backshift',
  'backside',
  'backslid',
  'backspace',
  'backspin',
  'backstab',
  'backstage',
  'backtalk',
  'backtrack',
  'backup',
  'backward',
  'backwash',
  'backwater',
  'backyard',
  'bacon',
  'bacteria',
  'bacterium',
  'badass',
  'badge',
  'badland',
  'badly',
  'badness',
  'baffle',
  'baffling',
  'bagel',
  'bagful',
  'baggage',
  'bagged',
  'baggie',
  'bagginess',
  'bagging',
  'baggy',
  'bagpipe',
  'baguette',
  'baked',
  'bakery',
  'bakeshop',
  'baking',
  'balance',
  'balancing',
  'balcony',
  'balmy',
  'balsamic',
  'bamboo',
  'banana',
  'banish',
  'banister',
  'banjo',
  'bank',
  'bankable',
  'bankbook',
  'banking',
  'banknote',
  'bankroll',
  'banner',
  'bannister',
  'banshee',
  'bantha',
  'barbecue',
  'barbed',
  'barbell',
  'barber',
  'barcode',
  'barge',
  'bargraph',
  'barista',
  'baritone',
  'barley',
  'barmaid',
  'barman',
  'barn',
  'barometer',
  'barrack',
  'barracuda',
  'barrel',
  'barrette',
  'barricade',
  'barrier',
  'barstool',
  'bartender',
  'barterer',
  'bash',
  'basically',
  'basics',
  'basil',
  'basin',
  'basis',
  'basket',
  'batboy',
  'batch',
  'bath',
  'baton',
  'bats',
  'battalion',
  'battered',
  'battering',
  'battery',
  'batting',
  'battle',
  'bauble',
  'bazooka',
  'blabber',
  'bladder',
  'blade',
  'blah',
  'blame',
  'blaming',
  'blanching',
  'blandness',
  'blank',
  'blaspheme',
  'blasphemy',
  'blast',
  'blatancy',
  'blatantly',
  'blazer',
  'blazing',
  'bleach',
  'bleak',
  'bleep',
  'blemish',
  'blend',
  'bless',
  'blighted',
  'blimp',
  'bling',
  'blinked',
  'blinker',
  'blinking',
  'blinks',
  'blip',
  'blissful',
  'blitz',
  'blizzard',
  'bloated',
  'bloating',
  'blob',
  'blog',
  'bloomers',
  'blooming',
  'blooper',
  'blossom',
  'blot',
  'blouse',
  'blubber',
  'bluff',
  'bluish',
  'blunderbuss',
  'blundering',
  'blunt',
  'blurb',
  'blurred',
  'blurry',
  'blurt',
  'blush',
  'blustery',
  'boaster',
  'boastful',
  'boasting',
  'boat',
  'bobbed',
  'bobbing',
  'bobble',
  'bobcat',
  'bobsled',
  'bobtail',
  'bodacious',
  'body',
  'bogged',
  'boggle',
  'bogus',
  'boil',
  'bok',
  'bolster',
  'bolt',
  'bonanza',
  'bonded',
  'bonding',
  'bondless',
  'bone',
  'bonfire',
  'bonnet',
  'bonsai',
  'bonus',
  'bony',
  'boogeyman',
  'boogieman',
  'book',
  'boondocks',
  'booted',
  'booth',
  'bootie',
  'booting',
  'bootlace',
  'bootleg',
  'boots',
  'boozy',
  'borax',
  'boring',
  'borough',
  'borrower',
  'borrowing',
  'boss',
  'botanical',
  'botanist',
  'botany',
  'botch',
  'both',
  'bottle',
  'bottling',
  'bottom',
  'bounce',
  'bouncing',
  'bouncy',
  'bounding',
  'boundless',
  'bountiful',
  'bounty',
  'bouquet',
  'boutique',
  'bovine',
  'boxcar',
  'boxer',
  'boxing',
  'boxlike',
  'boxy',
  'breach',
  'breath',
  'breeches',
  'breeching',
  'breeder',
  'breeding',
  'breeze',
  'breezy',
  'brethren',
  'brewery',
  'brewing',
  'briar',
  'bribe',
  'brick',
  'bride',
  'bridged',
  'brigade',
  'bright',
  'brilliant',
  'brimming',
  'bring',
  'brink',
  'brisket',
  'briskly',
  'briskness',
  'bristle',
  'brittle',
  'broadband',
  'broadcast',
  'broaden',
  'broadly',
  'broadness',
  'broadside',
  'broadways',
  'broiler',
  'broiling',
  'broken',
  'broker',
  'bronchial',
  'bronco',
  'bronze',
  'bronzing',
  'brook',
  'broom',
  'brought',
  'browbeat',
  'brownnose',
  'browse',
  'browsing',
  'bruising',
  'brunch',
  'brunette',
  'brunt',
  'brush',
  'Brussels',
  'brute',
  'brutishly',
  'bubble',
  'bubbling',
  'bubbly',
  'buccaneer',
  'bucked',
  'bucket',
  'buckle',
  'buckshot',
  'buckskin',
  'bucktooth',
  'buckwheat',
  'buddhism',
  'buddhist',
  'budding',
  'buddy',
  'budget',
  'buffalo',
  'buffed',
  'buffer',
  'buffing',
  'buffoon',
  'buggy',
  'bulb',
  'bulge',
  'bulginess',
  'bulgur',
  'bulk',
  'bulldog',
  'bulldozer',
  'bullfight',
  'bullfrog',
  'bullhorn',
  'bullion',
  'bullish',
  'bullpen',
  'bullring',
  'bullseye',
  'bullwhip',
  'bully',
  'bunch',
  'bundle',
  'bungee',
  'bunion',
  'bunkbed',
  'bunkhouse',
  'bunkmate',
  'bunny',
  'bunt',
  'busboy',
  'bush',
  'busily',
  'busload',
  'bust',
  'busybody',
  'buzz',
  'cabana',
  'cabbage',
  'cabbie',
  'cabdriver',
  'cable',
  'caboose',
  'cache',
  'cackle',
  'cacti',
  'cactus',
  'caddie',
  'caddy',
  'cadet',
  'cadillac',
  'cadmium',
  'cage',
  'cahoots',
  'cake',
  'calamari',
  'calamity',
  'calcium',
  'calculate',
  'calculus',
  'caliber',
  'calibrate',
  'calm',
  'caloric',
  'calorie',
  'calzone',
  'camcorder',
  'cameo',
  'camera',
  'camisole',
  'camper',
  'campfire',
  'camping',
  'campsite',
  'campus',
  'canal',
  'canary',
  'cancel',
  'candied',
  'candle',
  'candy',
  'cane',
  'canine',
  'canister',
  'cannabis',
  'canned',
  'canning',
  'cannon',
  'cannot',
  'canola',
  'canon',
  'canopener',
  'canopy',
  'canteen',
  'canyon',
  'capable',
  'capably',
  'capacity',
  'cape',
  'capillary',
  'capital',
  'capitol',
  'capped',
  'capricorn',
  'capsize',
  'capsule',
  'caption',
  'captivate',
  'captive',
  'captivity',
  'capture',
  'caramel',
  'carat',
  'caravan',
  'carbon',
  'cardboard',
  'carded',
  'cardiac',
  'cardigan',
  'cardinal',
  'cardstock',
  'carefully',
  'caregiver',
  'careless',
  'caress',
  'caretaker',
  'cargo',
  'caring',
  'carless',
  'carload',
  'carmaker',
  'carnage',
  'carnation',
  'carnival',
  'carnivore',
  'carol',
  'carpenter',
  'carpentry',
  'carpool',
  'carport',
  'carried',
  'carrot',
  'carrousel',
  'carry',
  'cartel',
  'cartload',
  'carton',
  'cartoon',
  'cartridge',
  'cartwheel',
  'carve',
  'carving',
  'carwash',
  'cascade',
  'case',
  'cash',
  'casing',
  'casino',
  'casket',
  'cassette',
  'casually',
  'casualty',
  'catacomb',
  'catalog',
  'catalyst',
  'catalyze',
  'catapult',
  'cataract',
  'catatonic',
  'catcall',
  'catchable',
  'catcher',
  'catching',
  'catchy',
  'caterer',
  'catering',
  'catfight',
  'catfish',
  'cathedral',
  'cathouse',
  'catlike',
  'catnap',
  'catnip',
  'catsup',
  'cattail',
  'cattishly',
  'cattle',
  'catty',
  'catwalk',
  'caucasian',
  'caucus',
  'causal',
  'causation',
  'cause',
  'causing',
  'cauterize',
  'caution',
  'cautious',
  'cavalier',
  'cavalry',
  'caviar',
  'cavity',
  'cedar',
  'celery',
  'celestial',
  'celibacy',
  'celibate',
  'celtic',
  'cement',
  'census',
  'ceramics',
  'ceremony',
  'certainly',
  'certainty',
  'certified',
  'certify',
  'cesarean',
  'cesspool',
  'chafe',
  'chaffing',
  'chain',
  'chair',
  'chalice',
  'challenge',
  'chamber',
  'champagne',
  'champion',
  'chance',
  'change',
  'channel',
  'chant',
  'chaos',
  'chaperone',
  'chaplain',
  'chapped',
  'chaps',
  'chapter',
  'character',
  'charbroil',
  'charcoal',
  'charger',
  'charging',
  'chariot',
  'charity',
  'charm',
  'charred',
  'charter',
  'charting',
  'chase',
  'chasing',
  'chaste',
  'chastise',
  'chastity',
  'chatroom',
  'chatter',
  'chatting',
  'chatty',
  'cheating',
  'cheddar',
  'cheek',
  'cheer',
  'cheese',
  'cheesy',
  'chef',
  'chemicals',
  'chemist',
  'chemo',
  'cherisher',
  'cherub',
  'chess',
  'chest',
  'chevron',
  'chevy',
  'chewable',
  'chewer',
  'chewing',
  'chewy',
  'chief',
  'chihuahua',
  'childcare',
  'childhood',
  'childish',
  'childless',
  'childlike',
  'childproof',
  'chili',
  'chill',
  'chimp',
  'chip',
  'chirping',
  'chirpy',
  'chitchat',
  'chivalry',
  'chive',
  'chloride',
  'chlorine',
  'choice',
  'chokehold',
  'choking',
  'chomp',
  'choosing',
  'choosy',
  'chop',
  'chosen',
  'chowder',
  'chowtime',
  'chrome',
  'chubby',
  'chuck',
  'chug',
  'chummy',
  'chump',
  'chunk',
  'churn',
  'chute',
  'cider',
  'cilantro',
  'cinch',
  'cinema',
  'cinnamon',
  'circle',
  'circling',
  'circular',
  'circulate',
  'circus',
  'citable',
  'citadel',
  'citation',
  'citizen',
  'citric',
  'citrus',
  'city',
  'civic',
  'civil',
  'clad',
  'claim',
  'clambake',
  'clammy',
  'clamor',
  'clamp',
  'clamshell',
  'clang',
  'clanking',
  'clapped',
  'clapper',
  'clapping',
  'clarify',
  'clarinet',
  'clarity',
  'clash',
  'clasp',
  'class',
  'clatter',
  'clause',
  'clavicle',
  'claw',
  'clay',
  'clean',
  'clear',
  'cleat',
  'cleaver',
  'cleft',
  'clench',
  'clergyman',
  'clerical',
  'clerk',
  'clever',
  'clicker',
  'client',
  'climate',
  'climatic',
  'cling',
  'clinic',
  'clinking',
  'clip',
  'clique',
  'cloak',
  'clobber',
  'clock',
  'clone',
  'cloning',
  'closable',
  'closure',
  'clothes',
  'clothing',
  'cloud',
  'clover',
  'clubbed',
  'clubbing',
  'clubhouse',
  'clump',
  'clumsily',
  'clumsy',
  'clunky',
  'clustered',
  'clutch',
  'clutter',
  'coach',
  'coagulate',
  'coastal',
  'coaster',
  'coasting',
  'coastland',
  'coastline',
  'coat',
  'coauthor',
  'cobalt',
  'cobbler',
  'cobweb',
  'cocoa',
  'coconut',
  'cod',
  'coeditor',
  'coerce',
  'coexist',
  'coffee',
  'cofounder',
  'cognition',
  'cognitive',
  'cogwheel',
  'coherence',
  'coherent',
  'cohesive',
  'coil',
  'coke',
  'cola',
  'cold',
  'coleslaw',
  'coliseum',
  'collage',
  'collapse',
  'collar',
  'collected',
  'collector',
  'collide',
  'collie',
  'collision',
  'colonial',
  'colonist',
  'colonize',
  'colony',
  'colossal',
  'colt',
  'coma',
  'come',
  'comeback',
  'comedian',
  'comedy',
  'comet',
  'comfy',
  'comic',
  'coming',
  'comma',
  'commence',
  'commend',
  'comment',
  'commerce',
  'commode',
  'commodity',
  'commodore',
  'common',
  'commotion',
  'commute',
  'commuting',
  'compacted',
  'compacter',
  'compactly',
  'compactor',
  'companion',
  'company',
  'compare',
  'compel',
  'compile',
  'comply',
  'component',
  'composed',
  'composer',
  'composite',
  'compost',
  'composure',
  'compound',
  'compress',
  'comprised',
  'computer',
  'computing',
  'comrade',
  'concave',
  'conceal',
  'conceded',
  'concept',
  'concerned',
  'concert',
  'conch',
  'concierge',
  'concise',
  'conclude',
  'concoct',
  'concrete',
  'concur',
  'condense',
  'condiment',
  'condition',
  'condone',
  'conducive',
  'conductor',
  'conduit',
  'cone',
  'confess',
  'confetti',
  'confidant',
  'confident',
  'confider',
  'confiding',
  'configure',
  'confined',
  'confining',
  'confirm',
  'conflict',
  'conform',
  'confound',
  'confront',
  'confused',
  'confusing',
  'confusion',
  'congenial',
  'congested',
  'congrats',
  'congress',
  'conical',
  'conjoined',
  'conjure',
  'conjuror',
  'connected',
  'connector',
  'consensus',
  'consent',
  'console',
  'consoling',
  'consonant',
  'constable',
  'constant',
  'constrain',
  'constrict',
  'construct',
  'consult',
  'consumer',
  'consuming',
  'contact',
  'container',
  'contempt',
  'contend',
  'contender',
  'content',
  'contest',
  'context',
  'contort',
  'contour',
  'contrite',
  'control',
  'contusion',
  'convene',
  'convent',
  'copartner',
  'cope',
  'copied',
  'copier',
  'copilot',
  'coping',
  'copious',
  'copper',
  'copy',
  'coral',
  'cork',
  'cornball',
  'cornbread',
  'corncob',
  'corndog',
  'cornea',
  'corned',
  'corner',
  'cornfield',
  'cornflake',
  'cornhusk',
  'cornmeal',
  'cornstalk',
  'cornucopia',
  'corny',
  'coronary',
  'coroner',
  'corporal',
  'corporate',
  'corral',
  'correct',
  'corridor',
  'corrode',
  'corroding',
  'corrosive',
  'corsage',
  'corset',
  'cortex',
  'cosigner',
  'cosmetics',
  'cosmic',
  'cosmos',
  'cosponsor',
  'cost',
  'cottage',
  'cotton',
  'couch',
  'cough',
  'could',
  'countable',
  'countdown',
  'counting',
  'countless',
  'country',
  'county',
  'courier',
  'covenant',
  'cover',
  'coveted',
  'coveting',
  'coyness',
  'cozily',
  'coziness',
  'cozy',
  'crabbing',
  'crabgrass',
  'crablike',
  'crabmeat',
  'cradle',
  'cradling',
  'crafter',
  'craftily',
  'craftsman',
  'craftwork',
  'crafty',
  'cramp',
  'crane',
  'cranial',
  'cranium',
  'crank',
  'crate',
  'crave',
  'craving',
  'crawfish',
  'crawlers',
  'crawling',
  'crayfish',
  'crayon',
  'crazed',
  'crazily',
  'craziness',
  'crazy',
  'creamed',
  'creamer',
  'creamlike',
  'creamy',
  'creasing',
  'create',
  'creation',
  'creative',
  'creature',
  'credible',
  'credibly',
  'credit',
  'creed',
  'creme',
  'creole',
  'crepe',
  'crept',
  'crescent',
  'crested',
  'cresting',
  'crestless',
  'crevice',
  'crewless',
  'crewman',
  'crewmate',
  'crib',
  'cricket',
  'cried',
  'crier',
  'crimp',
  'crimson',
  'cringe',
  'cringing',
  'crinkle',
  'crinkly',
  'crisped',
  'crisping',
  'crisply',
  'crispness',
  'crispy',
  'criteria',
  'critter',
  'croak',
  'crock',
  'crook',
  'croon',
  'crop',
  'cross',
  'crouch',
  'crouton',
  'crowbar',
  'crowd',
  'crown',
  'crucial',
  'crudely',
  'crudeness',
  'cruelly',
  'cruelness',
  'cruelty',
  'crumb',
  'crummiest',
  'crummy',
  'crumpet',
  'crumpled',
  'cruncher',
  'crunching',
  'crunchy',
  'crusader',
  'crushable',
  'crushed',
  'crusher',
  'crushing',
  'crust',
  'crux',
  'crying',
  'cryptic',
  'crystal',
  'cubbyhole',
  'cube',
  'cubical',
  'cubicle',
  'cucumber',
  'cuddle',
  'cuddly',
  'cufflink',
  'culinary',
  'culminate',
  'culpable',
  'culprit',
  'cultivate',
  'cultural',
  'culture',
  'cupbearer',
  'cupcake',
  'cupid',
  'cupped',
  'cupping',
  'curable',
  'curator',
  'curdle',
  'cure',
  'curfew',
  'curing',
  'curled',
  'curler',
  'curliness',
  'curling',
  'curly',
  'curry',
  'curse',
  'cursive',
  'cursor',
  'curtain',
  'curtly',
  'curtsy',
  'curvature',
  'curve',
  'curvy',
  'cushy',
  'cusp',
  'cussed',
  'custard',
  'custodian',
  'custody',
  'customary',
  'customer',
  'customize',
  'customs',
  'cutback',
  'cute',
  'cutesy',
  'cuticle',
  'cutlery',
  'cutlet',
  'cutoff',
  'cutout',
  'cutter',
  'cutting',
  'cyan',
  'cycle',
  'cyclic',
  'cycling',
  'cyclist',
  'cylinder',
  'cymbal',
  'cynic',
  'cyst',
]

// Pronounceable consonant-vowel patterns
const VOWELS = 'aeiou'
const CONSONANTS = 'bcdfghjklmnpqrstvwxyz'

// Cryptographically secure password generation
export function generatePassword(options: PasswordOptions): string {
  let charset = ''
  if (options.uppercase) charset += CHAR_SETS.uppercase
  if (options.lowercase) charset += CHAR_SETS.lowercase
  if (options.numbers) charset += CHAR_SETS.numbers
  if (options.symbols) charset += CHAR_SETS.symbols

  if (charset === '') {
    throw new Error('At least one character set must be selected')
  }

  const password: string[] = []
  const randomValues = new Uint32Array(options.length)
  crypto.getRandomValues(randomValues)

  for (let i = 0; i < options.length; i++) {
    const randomIndex = randomValues[i] % charset.length
    password.push(charset[randomIndex])
  }

  return password.join('')
}

// Generate a diceware passphrase
export function generateDiceware(wordCount = 6, separator = '-'): string {
  const words: string[] = []
  const randomValues = new Uint32Array(wordCount)
  crypto.getRandomValues(randomValues)

  for (let i = 0; i < wordCount; i++) {
    const randomIndex = randomValues[i] % DICEWARE_WORDS.length
    words.push(DICEWARE_WORDS[randomIndex])
  }

  return words.join(separator)
}

// Generate a pronounceable password
export function generatePronounceable(length: number): string {
  const password: string[] = []
  const randomValues = new Uint32Array(length)
  crypto.getRandomValues(randomValues)

  for (let i = 0; i < length; i++) {
    // Alternate between consonants and vowels for pronounceability
    const useVowel = i % 2 === 1
    const charset = useVowel ? VOWELS : CONSONANTS
    const randomIndex = randomValues[i] % charset.length
    password.push(charset[randomIndex])
  }

  return password.join('')
}

// Password templates
export const PASSWORD_TEMPLATES: PasswordTemplate[] = [
  {
    id: 'banking',
    name: 'Banking (High Security)',
    description: '16+ chars, uppercase, lowercase, numbers, symbols',
    pattern: 'Aa1!-Aa1!-Aa1!-Aa1!',
    example: 'Xk5@-Pm7#-Qs2&-Lv9*',
    category: 'banking',
  },
  {
    id: 'social',
    name: 'Social Media',
    description: '12+ chars, mixed case, numbers',
    pattern: 'Aa1Aa1Aa1Aa1',
    example: 'Tp3Mk8Qr2Zv7',
    category: 'social',
  },
  {
    id: 'wifi',
    name: 'WiFi Network',
    description: '16+ chars, no special chars',
    pattern: 'Aa1aa1Aa1aa1Aa1a',
    example: 'Xk5pm7Qs2lv9Hn4x',
    category: 'wifi',
  },
  {
    id: 'email',
    name: 'Email Account',
    description: '14+ chars, mixed case, numbers, symbols',
    pattern: 'Aa1!Aa1!Aa1!Aa1',
    example: 'Tp3@Mk8#Qr2&Zv7',
    category: 'email',
  },
  {
    id: 'pin',
    name: 'PIN Code',
    description: '6-8 digit numeric code',
    pattern: '111111',
    example: '842759',
    category: 'custom',
  },
]

// Generate password from template
export function generateFromTemplate(templateId: string): string {
  const template = PASSWORD_TEMPLATES.find((t) => t.id === templateId)
  if (!template) {
    throw new Error('Template not found')
  }

  const { pattern } = template
  const password: string[] = []
  const randomValues = new Uint32Array(pattern.length)
  crypto.getRandomValues(randomValues)

  let randomIndex = 0
  for (const char of pattern) {
    if (char === 'A') {
      // Uppercase letter
      const index = randomValues[randomIndex++] % CHAR_SETS.uppercase.length
      password.push(CHAR_SETS.uppercase[index])
    } else if (char === 'a') {
      // Lowercase letter
      const index = randomValues[randomIndex++] % CHAR_SETS.lowercase.length
      password.push(CHAR_SETS.lowercase[index])
    } else if (char === '1') {
      // Number
      const index = randomValues[randomIndex++] % CHAR_SETS.numbers.length
      password.push(CHAR_SETS.numbers[index])
    } else if (char === '!') {
      // Symbol
      const index = randomValues[randomIndex++] % CHAR_SETS.symbols.length
      password.push(CHAR_SETS.symbols[index])
    } else {
      // Keep literal character (like '-')
      password.push(char)
    }
  }

  return password.join('')
}

// Calculate password strength using zxcvbn
export function calculateStrength(password: string): StrengthResult {
  if (!password) {
    return {
      score: 0,
      label: 'No Password',
      color: 'gray.500',
      feedback: ['Enter a password to see strength analysis'],
      entropy: 0,
      crackTime: 'Instant',
      crackTimeSeconds: 0,
    }
  }

  const result = zxcvbn(password)
  const feedback: string[] = []

  // Extract feedback from zxcvbn
  if (result.feedback.warning) {
    feedback.push(result.feedback.warning)
  }
  if (result.feedback.suggestions && result.feedback.suggestions.length > 0) {
    feedback.push(...result.feedback.suggestions)
  }

  // Calculate entropy (bits)
  const entropy = Math.log2(getCharsetSize(password) ** password.length)

  // Format crack time display (offline_slow_hashing_1e4_per_second is always a number)
  const crackTimeSecondsValue =
    typeof result.crack_times_seconds.offline_slow_hashing_1e4_per_second === 'number'
      ? result.crack_times_seconds.offline_slow_hashing_1e4_per_second
      : 0
  const crackTime = formatCrackTime(crackTimeSecondsValue)
  const crackTimeSeconds = crackTimeSecondsValue

  // Map zxcvbn score (0-4) to our labels and colors
  const scoreMap = [
    { label: 'Very Weak', color: '#ef4444' }, // red-500
    { label: 'Weak', color: '#f97316' }, // orange-500
    { label: 'Fair', color: '#eab308' }, // yellow-500
    { label: 'Strong', color: '#22c55e' }, // green-500
    { label: 'Very Strong', color: '#10b981' }, // emerald-500
  ]

  const { label, color } = scoreMap[result.score]

  return {
    score: result.score,
    label,
    color,
    feedback: feedback.length > 0 ? feedback : ['Password strength analyzed'],
    entropy: Math.round(entropy * 10) / 10,
    crackTime,
    crackTimeSeconds,
  }
}

// Get charset size based on characters used
function getCharsetSize(password: string): number {
  let size = 0
  if (/[a-z]/.test(password)) size += 26 // lowercase
  if (/[A-Z]/.test(password)) size += 26 // uppercase
  if (/[0-9]/.test(password)) size += 10 // numbers
  if (/[^a-zA-Z0-9]/.test(password)) size += 33 // symbols
  return size || 1
}

// Format crack time in human-readable format
function formatCrackTime(seconds: number): string {
  if (seconds < 1) return 'Instant'
  if (seconds < 60) return `${Math.round(seconds)} seconds`
  if (seconds < 3600) return `${Math.round(seconds / 60)} minutes`
  if (seconds < 86400) return `${Math.round(seconds / 3600)} hours`
  if (seconds < 2592000) return `${Math.round(seconds / 86400)} days`
  if (seconds < 31536000) return `${Math.round(seconds / 2592000)} months`
  if (seconds < 3153600000) return `${Math.round(seconds / 31536000)} years`
  return 'Centuries'
}

// Password History Management
const HISTORY_KEY = 'password-generator-history'
const MAX_HISTORY = 10

export function savePasswordToHistory(password: string): void {
  try {
    const history = getPasswordHistory()
    const strength = calculateStrength(password)

    const entry: PasswordHistory = {
      password,
      timestamp: Date.now(),
      strength,
      favorite: false,
      length: password.length,
    }

    // Add to beginning, remove duplicates
    const filtered = history.filter((h) => h.password !== password)
    const updated = [entry, ...filtered].slice(0, MAX_HISTORY)

    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated))
  } catch (error) {
    console.error('Failed to save password to history:', error)
  }
}

export function getPasswordHistory(): PasswordHistory[] {
  try {
    const stored = localStorage.getItem(HISTORY_KEY)
    if (!stored) return []
    const parsed: unknown = JSON.parse(stored)
    if (!Array.isArray(parsed)) return []
    return parsed as PasswordHistory[]
  } catch {
    return []
  }
}

export function toggleFavorite(password: string): void {
  try {
    const history = getPasswordHistory()
    const updated = history.map((entry) =>
      entry.password === password ? { ...entry, favorite: !entry.favorite } : entry
    )
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated))
  } catch (error) {
    console.error('Failed to toggle favorite:', error)
  }
}

export function deleteFromHistory(password: string): void {
  try {
    const history = getPasswordHistory()
    const filtered = history.filter((h) => h.password !== password)
    localStorage.setItem(HISTORY_KEY, JSON.stringify(filtered))
  } catch (error) {
    console.error('Failed to delete from history:', error)
  }
}

export function clearHistory(): void {
  try {
    localStorage.removeItem(HISTORY_KEY)
  } catch (error) {
    console.error('Failed to clear history:', error)
  }
}

export function exportHistoryToCSV(history: PasswordHistory[]): string {
  const headers = [
    'Password',
    'Length',
    'Strength',
    'Entropy (bits)',
    'Crack Time',
    'Favorite',
    'Date',
  ]
  const rows = history.map((entry) => [
    entry.password,
    entry.length.toString(),
    entry.strength.label,
    entry.strength.entropy?.toString() || 'N/A',
    entry.strength.crackTime || 'N/A',
    entry.favorite ? 'Yes' : 'No',
    new Date(entry.timestamp).toLocaleString(),
  ])

  const csv = [headers, ...rows].map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')

  return csv
}

// Have I Been Pwned (HIBP) k-anonymity check
export async function checkPasswordPwned(password: string): Promise<{
  isPwned: boolean
  count: number
  error?: string
}> {
  try {
    // Hash the password with SHA-1
    const encoder = new TextEncoder()
    const data = encoder.encode(password)
    const hashBuffer = await crypto.subtle.digest('SHA-1', data)
    const hashArray = Array.from(new Uint8Array(hashBuffer))
    const hashHex = hashArray
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
      .toUpperCase()

    // Use k-anonymity: send only first 5 chars of hash
    const prefix = hashHex.slice(0, 5)
    const suffix = hashHex.slice(5)

    const response = await fetch(`https://api.pwnedpasswords.com/range/${prefix}`)

    if (!response.ok) {
      return { isPwned: false, count: 0, error: 'Failed to check password' }
    }

    const text = await response.text()
    const lines = text.split('\n')

    // Check if our suffix is in the results
    for (const line of lines) {
      const [hashSuffix, countStr] = line.split(':')
      if (hashSuffix === suffix) {
        return { isPwned: true, count: parseInt(countStr.trim(), 10) }
      }
    }

    return { isPwned: false, count: 0 }
  } catch (error) {
    return {
      isPwned: false,
      count: 0,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// Common password blacklist (top 100 most common)
const COMMON_PASSWORDS = [
  '123456',
  'password',
  '123456789',
  '12345678',
  '12345',
  '1234567',
  '1234567890',
  'qwerty',
  'abc123',
  '111111',
  '123123',
  'admin',
  'letmein',
  'welcome',
  'monkey',
  'dragon',
  'master',
  'sunshine',
  'princess',
  'qwerty123',
  'password1',
  'football',
  'iloveyou',
  'admin123',
  'welcome123',
  'monkey123',
  'login',
  'starwars',
  '123qwe',
  'dragon123',
]

export function checkCommonPassword(password: string): boolean {
  const lower = password.toLowerCase()
  return COMMON_PASSWORDS.some((common) => lower.includes(common))
}

// Generate bulk passwords with uniqueness guarantee
export function generateBulkPasswords(count: number, options: PasswordOptions): string[] {
  const passwords = new Set<string>()
  let attempts = 0
  const maxAttempts = count * 10 // Prevent infinite loop

  while (passwords.size < count && attempts < maxAttempts) {
    const password = generatePassword(options)
    passwords.add(password)
    attempts++
  }

  return Array.from(passwords)
}

// Export bulk passwords to CSV with metadata
export function exportBulkToCSV(passwords: string[]): string {
  const headers = ['Password', 'Length', 'Strength', 'Entropy (bits)', 'Crack Time', 'Generated At']
  const rows = passwords.map((password) => {
    const strength = calculateStrength(password)
    return [
      password,
      password.length.toString(),
      strength.label,
      strength.entropy?.toString() || 'N/A',
      strength.crackTime || 'N/A',
      new Date().toISOString(),
    ]
  })

  const csv = [headers, ...rows].map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\n')

  return csv
}
