import type { Metadata } from 'next'
import Script from 'next/script'
import { generateToolBreadcrumbs, generateToolMetadata } from '@/lib/metadata'
import {
  generateBreadcrumbSchema,
  generateFAQSchema,
  generateHowToSchema,
} from '@/lib/structured-data'

export const metadata: Metadata = generateToolMetadata({
  title: 'QR Code Generator',
  description:
    'Free online QR code generator for URLs, text, WiFi, and more. Create custom QR codes with logos, colors, and download in high resolution. Fast, secure, and privacy-focused QR code maker.',
  keywords: [
    'qr code generator',
    'create qr code',
    'qr code maker',
    'generate qr',
    'custom qr code',
    'qr code creator',
    'free qr generator',
    'wifi qr code',
    'url to qr',
    'qr code online',
    'barcode generator',
    'qr scanner',
  ],
  category: 'utilities',
  path: '/tools/qr-code',
})

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://supertool.id'
const breadcrumbs = generateToolBreadcrumbs('QR Code Generator')

const faqs = [
  {
    question: 'How do I create a QR code for free?',
    answer:
      'Simply enter your URL, text, WiFi credentials, or other data into our generator, customize the design if desired, and click Generate. Your QR code will be created instantly in your browser. You can download it as PNG or SVG format at high resolution, completely free with no watermarks or registration required.',
  },
  {
    question: 'What types of QR codes can I generate?',
    answer:
      'Our generator supports multiple QR code types including URLs/links, plain text, WiFi credentials, contact information (vCard), email addresses, phone numbers, SMS messages, and location coordinates. Each type is optimized for its specific use case with appropriate data formatting.',
  },
  {
    question: 'Can I customize the QR code design and colors?',
    answer:
      'Yes! You can customize foreground and background colors, add your logo or icon to the center, adjust the error correction level for better scanning reliability, and choose between different output formats (PNG, SVG). All customizations maintain QR code scannability across devices.',
  },
  {
    question: 'Are the QR codes generated permanently valid?',
    answer:
      'Yes, static QR codes generated by our tool are permanent and never expire. Once created, they will work forever as long as the linked content (like a URL) remains accessible. The QR code data is encoded directly into the image, requiring no external database or tracking service.',
  },
  {
    question: 'What is the best size and resolution for QR codes?',
    answer:
      'For digital use, 300x300 to 500x500 pixels is sufficient. For print materials, we recommend at least 1000x1000 pixels or using SVG format which scales infinitely without quality loss. The minimum recommended print size is 2cm x 2cm (0.8" x 0.8") to ensure reliable scanning on mobile devices.',
  },
]

const howToSteps = [
  {
    name: 'Enter Your Content',
    text: 'Type or paste the content you want to encode into a QR code. This can be a website URL, plain text, WiFi credentials, contact information (vCard), email address, phone number, or location coordinates.',
  },
  {
    name: 'Customize Design (Optional)',
    text: 'Personalize your QR code by changing the foreground and background colors, adjusting the error correction level for better scanning reliability, or uploading a logo to display in the center of the QR code.',
  },
  {
    name: 'Generate QR Code',
    text: 'Click the "Generate QR Code" button to create your custom QR code instantly. The code is generated entirely in your browser with no server uploads, ensuring complete privacy and security.',
  },
  {
    name: 'Download and Use',
    text: 'Download your QR code in PNG format for digital use or SVG format for print materials. The QR code is permanent and will work forever as long as the linked content remains accessible.',
  },
]

export default function QRCodeLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
      <Script
        id="breadcrumb-schema"
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe usage for JSON-LD structured data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(generateBreadcrumbSchema(breadcrumbs, baseUrl)),
        }}
      />
      <Script
        id="faq-schema"
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe usage for JSON-LD structured data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(generateFAQSchema(faqs)),
        }}
      />
      <Script
        id="howto-schema"
        type="application/ld+json"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe usage for JSON-LD structured data
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(
            generateHowToSchema(
              'How to Create a Custom QR Code',
              'Learn how to generate custom QR codes with our free online QR code generator. Create QR codes for URLs, WiFi, text, and more with optional color customization and logo embedding.',
              howToSteps,
              baseUrl,
              '/tools/qr-code'
            )
          ),
        }}
      />
    </>
  )
}
