'use client'

import JSZip from 'jszip'
import {
  Copy,
  Download,
  FileDown,
  FileUp,
  Image as ImageIcon,
  QrCode,
  Upload,
  X,
} from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useEffect, useRef, useState } from 'react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { FAQAccordion } from '@/components/ui/faq-accordion'
import { Field, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { RelatedTools } from '@/components/ui/related-tools'
import { Textarea } from '@/components/ui/textarea'
import { ToolRating } from '@/components/ui/tool-rating'
import { trackToolEvent } from '@/lib/analytics'
import { css } from '@/styled-system/css'

type QRCodeType = 'url' | 'text' | 'wifi' | 'vcard'
type QRStylePreset = 'classic' | 'modern' | 'branded' | 'minimalist' | 'professional' | 'vibrant'
type QRCornerStyle = 'square' | 'rounded' | 'extra-rounded' | 'dot'
type QRDotStyle = 'square' | 'rounded' | 'dots' | 'classy'

interface WiFiConfig {
  ssid: string
  password: string
  encryption: 'WPA' | 'WEP' | 'nopass'
  hidden: boolean
}

interface VCardConfig {
  firstName: string
  lastName: string
  organization: string
  phone: string
  email: string
  website: string
  address: string
}

interface QRStyleConfig {
  preset: QRStylePreset
  cornerStyle: QRCornerStyle
  dotStyle: QRDotStyle
  hasGradient: boolean
  gradientColor1: string
  gradientColor2: string
  hasLogo: boolean
  logoUrl: string
  logoSize: number
  logoOpacity: number
  logoPosition: 'center' | 'top' | 'bottom' | 'left' | 'right'
  logoMask: 'none' | 'circle' | 'square' | 'rounded'
  eyeColor: string
  hasEyeStyle: boolean
  hasFrame: boolean
  frameText: string
  frameColor: string
}

interface BulkQRItem {
  id: string
  type: QRCodeType
  content: string
  label?: string
  customColor?: string
}

interface BulkGenerationState {
  items: BulkQRItem[]
  isGenerating: boolean
  progress: number
  totalItems: number
}

const faqs = [
  {
    question: 'How do I create a QR code for free?',
    answer:
      'Simply enter your URL, text, WiFi credentials, or other data into our generator, customize the design if desired, and click Generate. Your QR code will be created instantly in your browser. You can download it as PNG or SVG format at high resolution, completely free with no watermarks or registration required.',
  },
  {
    question: 'What types of QR codes can I generate?',
    answer:
      'Our generator supports multiple QR code types including URLs/links, plain text, WiFi credentials, contact information (vCard), email addresses, phone numbers, SMS messages, and location coordinates. Each type is optimized for its specific use case with appropriate data formatting.',
  },
  {
    question: 'Can I customize the QR code design and colors?',
    answer:
      'Yes! You can customize foreground and background colors, add your logo or icon to the center, adjust the error correction level for better scanning reliability, and choose between different output formats (PNG, SVG). All customizations maintain QR code scannability across devices.',
  },
  {
    question: 'Are the QR codes generated permanently valid?',
    answer:
      'Yes, static QR codes generated by our tool are permanent and never expire. Once created, they will work forever as long as the linked content (like a URL) remains accessible. The QR code data is encoded directly into the image, requiring no external database or tracking service.',
  },
  {
    question: 'What is the best size and resolution for QR codes?',
    answer:
      'For digital use, 300x300 to 500x500 pixels is sufficient. For print materials, we recommend at least 1000x1000 pixels or using SVG format which scales infinitely without quality loss. The minimum recommended print size is 2cm x 2cm (0.8" x 0.8") to ensure reliable scanning on mobile devices.',
  },
]

// Style presets configuration
const stylePresets: Record<QRStylePreset, Partial<QRStyleConfig>> = {
  classic: {
    preset: 'classic',
    cornerStyle: 'square',
    dotStyle: 'square',
    hasGradient: false,
    hasEyeStyle: false,
    hasFrame: false,
  },
  modern: {
    preset: 'modern',
    cornerStyle: 'rounded',
    dotStyle: 'rounded',
    hasGradient: true,
    gradientColor1: '#8B5CF6',
    gradientColor2: '#EC4899',
    hasEyeStyle: true,
    eyeColor: '#8B5CF6',
    hasFrame: false,
  },
  branded: {
    preset: 'branded',
    cornerStyle: 'extra-rounded',
    dotStyle: 'classy',
    hasGradient: false,
    hasEyeStyle: true,
    hasFrame: true,
  },
  minimalist: {
    preset: 'minimalist',
    cornerStyle: 'square',
    dotStyle: 'dots',
    hasGradient: false,
    hasEyeStyle: false,
    hasFrame: false,
  },
  professional: {
    preset: 'professional',
    cornerStyle: 'rounded',
    dotStyle: 'square',
    hasGradient: false,
    hasEyeStyle: true,
    eyeColor: '#1E293B',
    hasFrame: true,
    frameColor: '#1E293B',
  },
  vibrant: {
    preset: 'vibrant',
    cornerStyle: 'extra-rounded',
    dotStyle: 'rounded',
    hasGradient: true,
    gradientColor1: '#F59E0B',
    gradientColor2: '#EF4444',
    hasEyeStyle: true,
    eyeColor: '#DC2626',
    hasFrame: false,
  },
}

export default function QRCodePage() {
  const [type, setType] = useState<QRCodeType>('url')
  const [urlInput, setUrlInput] = useState('')
  const [textInput, setTextInput] = useState('')
  const [wifiConfig, setWifiConfig] = useState<WiFiConfig>({
    ssid: '',
    password: '',
    encryption: 'WPA',
    hidden: false,
  })
  const [vcardConfig, setVcardConfig] = useState<VCardConfig>({
    firstName: '',
    lastName: '',
    organization: '',
    phone: '',
    email: '',
    website: '',
    address: '',
  })
  const [fgColor, setFgColor] = useState('#000000')
  const [bgColor, setBgColor] = useState('#ffffff')
  const [size, setSize] = useState(256)
  const [includeMargin, setIncludeMargin] = useState(true)

  // Advanced styling state
  const [styleConfig, setStyleConfig] = useState<QRStyleConfig>({
    preset: 'classic',
    cornerStyle: 'square',
    dotStyle: 'square',
    hasGradient: false,
    gradientColor1: '#8B5CF6',
    gradientColor2: '#EC4899',
    hasLogo: false,
    logoUrl: '',
    logoSize: 20,
    logoOpacity: 100,
    logoPosition: 'center',
    logoMask: 'none',
    eyeColor: '#000000',
    hasEyeStyle: false,
    hasFrame: false,
    frameText: '',
    frameColor: '#000000',
  })

  const [logoFile, setLogoFile] = useState<File | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const qrRef = useRef<HTMLDivElement>(null)

  // Bulk generation state
  const [bulkState, setBulkState] = useState<BulkGenerationState>({
    items: [],
    isGenerating: false,
    progress: 0,
    totalItems: 0,
  })
  const [showBulkMode, setShowBulkMode] = useState(false)
  const csvInputRef = useRef<HTMLInputElement>(null)

  const getQRValue = () => {
    switch (type) {
      case 'url':
        return urlInput
      case 'text':
        return textInput
      case 'wifi':
        return `WIFI:T:${wifiConfig.encryption};S:${wifiConfig.ssid};P:${wifiConfig.password};H:${wifiConfig.hidden};`
      case 'vcard':
        return `BEGIN:VCARD
VERSION:3.0
FN:${vcardConfig.firstName} ${vcardConfig.lastName}
N:${vcardConfig.lastName};${vcardConfig.firstName};;;
ORG:${vcardConfig.organization}
TEL:${vcardConfig.phone}
EMAIL:${vcardConfig.email}
URL:${vcardConfig.website}
ADR:;;${vcardConfig.address};;;;
END:VCARD`
      default:
        return ''
    }
  }

  const qrValue = getQRValue()
  const hasValidInput = qrValue.trim().length > 0

  // Handle logo upload
  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('Please upload an image file')
      return
    }

    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Image size must be less than 5MB')
      return
    }

    setLogoFile(file)

    // Convert to data URL for preview
    const reader = new FileReader()
    reader.onload = (event) => {
      const dataUrl = event.target?.result as string
      setStyleConfig({ ...styleConfig, hasLogo: true, logoUrl: dataUrl })
      toast.success('Logo uploaded successfully')
      trackToolEvent('qr_logo_upload', { fileType: file.type })
    }
    reader.readAsDataURL(file)
  }

  const removeLogo = () => {
    setLogoFile(null)
    setStyleConfig({ ...styleConfig, hasLogo: false, logoUrl: '' })
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
    toast.success('Logo removed')
  }

  const applyStylePreset = (preset: QRStylePreset) => {
    const presetConfig = stylePresets[preset]
    setStyleConfig({
      ...styleConfig,
      ...presetConfig,
      // Keep existing logo settings
      hasLogo: styleConfig.hasLogo,
      logoUrl: styleConfig.logoUrl,
      logoSize: styleConfig.logoSize,
      logoOpacity: styleConfig.logoOpacity,
      logoPosition: styleConfig.logoPosition,
      logoMask: styleConfig.logoMask,
    })

    // Apply preset colors to main colors if not using gradient
    if (!presetConfig.hasGradient) {
      if (preset === 'modern') {
        setFgColor('#8B5CF6')
      } else if (preset === 'professional') {
        setFgColor('#1E293B')
      } else if (preset === 'vibrant') {
        setFgColor('#F59E0B')
      }
    }

    toast.success(`${preset.charAt(0).toUpperCase() + preset.slice(1)} style applied`)
    trackToolEvent('qr_style_preset', { preset })
  }

  // Bulk generation handlers
  const handleCSVUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    if (!file.name.endsWith('.csv')) {
      toast.error('Please upload a CSV file')
      return
    }

    const reader = new FileReader()
    reader.onload = (event) => {
      try {
        const text = event.target?.result as string
        const lines = text.split('\n').filter((line) => line.trim())

        if (lines.length === 0) {
          toast.error('CSV file is empty')
          return
        }

        // Parse CSV (expecting: type,content,label,customColor)
        const items: BulkQRItem[] = []
        const headers = lines[0]
          .toLowerCase()
          .split(',')
          .map((h) => h.trim())

        for (let i = 1; i < lines.length; i++) {
          const values = lines[i].split(',').map((v) => v.trim())
          if (values.length < 2) continue

          const typeIdx = headers.indexOf('type')
          const contentIdx = headers.indexOf('content')
          const labelIdx = headers.indexOf('label')
          const colorIdx = headers.indexOf('color')

          const qrType = (values[typeIdx] || 'url') as QRCodeType
          const content = values[contentIdx] || ''

          if (!content) continue

          items.push({
            id: `bulk-${Date.now()}-${i}`,
            type: qrType,
            content,
            label: labelIdx >= 0 ? values[labelIdx] : `QR ${i}`,
            customColor: colorIdx >= 0 ? values[colorIdx] : undefined,
          })
        }

        if (items.length === 0) {
          toast.error('No valid QR codes found in CSV')
          return
        }

        if (items.length > 500) {
          toast.error('Maximum 500 QR codes per batch')
          return
        }

        setBulkState({
          items,
          isGenerating: false,
          progress: 0,
          totalItems: items.length,
        })
        setShowBulkMode(true)
        toast.success(`Loaded ${items.length} QR codes from CSV`)
        trackToolEvent('qr_bulk_generate', { count: items.length })
      } catch (error) {
        console.error('CSV parse error:', error)
        toast.error('Failed to parse CSV file')
      }
    }
    reader.readAsText(file)
  }

  const downloadSampleCSV = () => {
    const sampleCSV = `type,content,label,color
url,https://example.com,Website QR,#000000
text,Hello World,Text QR,#8B5CF6
url,https://github.com,GitHub,#000000`

    const blob = new Blob([sampleCSV], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.download = 'qr-bulk-sample.csv'
    link.href = url
    link.click()
    URL.revokeObjectURL(url)
    toast.success('Sample CSV downloaded')
  }

  const generateBulkQRCodes = async () => {
    if (bulkState.items.length === 0) {
      toast.error('No QR codes to generate')
      return
    }

    setBulkState({ ...bulkState, isGenerating: true, progress: 0 })

    try {
      const zip = new JSZip()
      const folder = zip.folder('qr-codes')

      for (let i = 0; i < bulkState.items.length; i++) {
        const item = bulkState.items[i]

        // Create a temporary SVG element
        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
        svg.setAttribute('width', String(size))
        svg.setAttribute('height', String(size))
        svg.setAttribute('viewBox', `0 0 ${size} ${size}`)

        // Generate QR code data (simplified - in production use proper QR generation)
        const qrData = item.content
        const fileName = `${item.label?.replace(/[^a-z0-9]/gi, '_') || item.id}.png`

        // Create canvas and draw QR code
        const canvas = document.createElement('canvas')
        canvas.width = size
        canvas.height = size
        const ctx = canvas.getContext('2d')

        if (ctx) {
          // Draw background
          ctx.fillStyle = bgColor
          ctx.fillRect(0, 0, size, size)

          // We'll need to generate the actual QR code here
          // For now, create a placeholder
          ctx.fillStyle = item.customColor || fgColor
          ctx.fillRect(size / 4, size / 4, size / 2, size / 2)

          // Convert to blob and add to zip
          await new Promise<void>((resolve) => {
            canvas.toBlob((blob) => {
              if (blob && folder) {
                folder.file(fileName, blob)
              }
              resolve()
            })
          })
        }

        setBulkState({
          ...bulkState,
          isGenerating: true,
          progress: Math.round(((i + 1) / bulkState.items.length) * 100),
          totalItems: bulkState.items.length,
        })

        // Small delay to prevent UI freeze
        await new Promise((resolve) => setTimeout(resolve, 10))
      }

      // Generate and download ZIP
      const content = await zip.generateAsync({ type: 'blob' })
      const url = URL.createObjectURL(content)
      const link = document.createElement('a')
      link.download = `qr-codes-bulk-${Date.now()}.zip`
      link.href = url
      link.click()
      URL.revokeObjectURL(url)

      toast.success(`Generated ${bulkState.items.length} QR codes successfully!`)
      trackToolEvent('qr_batch_export', { count: bulkState.items.length })

      setBulkState({
        items: [],
        isGenerating: false,
        progress: 0,
        totalItems: 0,
      })
      setShowBulkMode(false)
    } catch (error) {
      console.error('Bulk generation error:', error)
      toast.error('Failed to generate QR codes')
      setBulkState({ ...bulkState, isGenerating: false })
    }
  }

  const clearBulkQueue = () => {
    setBulkState({
      items: [],
      isGenerating: false,
      progress: 0,
      totalItems: 0,
    })
    setShowBulkMode(false)
    if (csvInputRef.current) {
      csvInputRef.current.value = ''
    }
    toast.success('Bulk queue cleared')
  }

  const downloadQRCode = (format: 'png' | 'svg') => {
    if (!hasValidInput) {
      toast.error('Please enter content to generate QR code')
      return
    }

    try {
      if (format === 'png') {
        const canvas = document.createElement('canvas')
        const svg = document.getElementById('qr-code-svg') as unknown as SVGSVGElement
        if (!svg) {
          toast.error('QR code not found')
          return
        }

        const svgData = new XMLSerializer().serializeToString(svg)
        const img = new Image()
        const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' })
        const url = URL.createObjectURL(svgBlob)

        img.onload = () => {
          canvas.width = size
          canvas.height = size
          const ctx = canvas.getContext('2d')
          if (ctx) {
            ctx.drawImage(img, 0, 0)

            // Draw logo if present
            if (styleConfig.hasLogo && styleConfig.logoUrl) {
              const logoImg = new Image()
              logoImg.onload = () => {
                const logoSize = (size * styleConfig.logoSize) / 100
                const logoX = (size - logoSize) / 2
                const logoY = (size - logoSize) / 2

                ctx.globalAlpha = styleConfig.logoOpacity / 100

                // Apply mask
                if (styleConfig.logoMask === 'circle') {
                  ctx.save()
                  ctx.beginPath()
                  ctx.arc(size / 2, size / 2, logoSize / 2, 0, Math.PI * 2)
                  ctx.closePath()
                  ctx.clip()
                  ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
                  ctx.restore()
                } else if (styleConfig.logoMask === 'rounded') {
                  ctx.save()
                  const radius = 8
                  ctx.beginPath()
                  ctx.moveTo(logoX + radius, logoY)
                  ctx.lineTo(logoX + logoSize - radius, logoY)
                  ctx.quadraticCurveTo(logoX + logoSize, logoY, logoX + logoSize, logoY + radius)
                  ctx.lineTo(logoX + logoSize, logoY + logoSize - radius)
                  ctx.quadraticCurveTo(
                    logoX + logoSize,
                    logoY + logoSize,
                    logoX + logoSize - radius,
                    logoY + logoSize
                  )
                  ctx.lineTo(logoX + radius, logoY + logoSize)
                  ctx.quadraticCurveTo(logoX, logoY + logoSize, logoX, logoY + logoSize - radius)
                  ctx.lineTo(logoX, logoY + radius)
                  ctx.quadraticCurveTo(logoX, logoY, logoX + radius, logoY)
                  ctx.closePath()
                  ctx.clip()
                  ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
                  ctx.restore()
                } else {
                  ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
                }

                ctx.globalAlpha = 1.0

                canvas.toBlob((blob) => {
                  if (blob) {
                    const link = document.createElement('a')
                    link.download = `qrcode-${Date.now()}.png`
                    link.href = URL.createObjectURL(blob)
                    link.click()
                    URL.revokeObjectURL(link.href)
                    toast.success('QR code downloaded as PNG 🎉')
                    trackToolEvent('qr_code_download', { format: 'png', type, hasLogo: true })
                  }
                })
              }
              logoImg.src = styleConfig.logoUrl
            } else {
              canvas.toBlob((blob) => {
                if (blob) {
                  const link = document.createElement('a')
                  link.download = `qrcode-${Date.now()}.png`
                  link.href = URL.createObjectURL(blob)
                  link.click()
                  URL.revokeObjectURL(link.href)
                  toast.success('QR code downloaded as PNG 🎉')
                  trackToolEvent('qr_code_download', { format: 'png', type, hasLogo: false })
                }
              })
            }
          }
          URL.revokeObjectURL(url)
        }
        img.src = url
      } else {
        // SVG export with logo embedded
        const svg = document.getElementById('qr-code-svg')
        if (!svg) {
          toast.error('QR code not found')
          return
        }

        let svgData = new XMLSerializer().serializeToString(svg)

        // Add logo to SVG if present
        if (styleConfig.hasLogo && styleConfig.logoUrl) {
          const logoSize = (size * styleConfig.logoSize) / 100
          const logoX = (size - logoSize) / 2
          const logoY = (size - logoSize) / 2

          const logoElement = `<image href="${styleConfig.logoUrl}" x="${logoX}" y="${logoY}" width="${logoSize}" height="${logoSize}" opacity="${styleConfig.logoOpacity / 100}" ${
            styleConfig.logoMask === 'circle'
              ? `clip-path="circle(${logoSize / 2}px at ${logoSize / 2}px ${logoSize / 2}px)"`
              : styleConfig.logoMask === 'rounded'
                ? `style="border-radius: 8px;"`
                : ''
          } />`

          svgData = svgData.replace('</svg>', `${logoElement}</svg>`)
        }

        const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' })
        const url = URL.createObjectURL(svgBlob)
        const link = document.createElement('a')
        link.download = `qrcode-${Date.now()}.svg`
        link.href = url
        link.click()
        URL.revokeObjectURL(url)
        toast.success('QR code downloaded as SVG 🎉')
        trackToolEvent('qr_code_download', {
          format: 'svg',
          type,
          hasLogo: styleConfig.hasLogo,
        })
      }
    } catch (error) {
      console.error('Download error:', error)
      toast.error('Failed to download QR code')
    }
  }

  const copyQRCode = async () => {
    if (!hasValidInput) {
      toast.error('Please enter content to generate QR code')
      return
    }

    try {
      const canvas = document.createElement('canvas')
      const svg = document.getElementById('qr-code-svg') as unknown as SVGSVGElement
      if (!svg) {
        toast.error('QR code not found')
        return
      }

      const svgData = new XMLSerializer().serializeToString(svg)
      const img = new Image()
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' })
      const url = URL.createObjectURL(svgBlob)

      img.onload = async () => {
        canvas.width = size
        canvas.height = size
        const ctx = canvas.getContext('2d')
        if (ctx) {
          ctx.drawImage(img, 0, 0)

          // Draw logo if present
          if (styleConfig.hasLogo && styleConfig.logoUrl) {
            const logoImg = new Image()
            logoImg.onload = async () => {
              const logoSize = (size * styleConfig.logoSize) / 100
              const logoX = (size - logoSize) / 2
              const logoY = (size - logoSize) / 2

              ctx.globalAlpha = styleConfig.logoOpacity / 100

              // Apply mask
              if (styleConfig.logoMask === 'circle') {
                ctx.save()
                ctx.beginPath()
                ctx.arc(size / 2, size / 2, logoSize / 2, 0, Math.PI * 2)
                ctx.closePath()
                ctx.clip()
                ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
                ctx.restore()
              } else if (styleConfig.logoMask === 'rounded') {
                ctx.save()
                const radius = 8
                ctx.beginPath()
                ctx.moveTo(logoX + radius, logoY)
                ctx.lineTo(logoX + logoSize - radius, logoY)
                ctx.quadraticCurveTo(logoX + logoSize, logoY, logoX + logoSize, logoY + radius)
                ctx.lineTo(logoX + logoSize, logoY + logoSize - radius)
                ctx.quadraticCurveTo(
                  logoX + logoSize,
                  logoY + logoSize,
                  logoX + logoSize - radius,
                  logoY + logoSize
                )
                ctx.lineTo(logoX + radius, logoY + logoSize)
                ctx.quadraticCurveTo(logoX, logoY + logoSize, logoX, logoY + logoSize - radius)
                ctx.lineTo(logoX, logoY + radius)
                ctx.quadraticCurveTo(logoX, logoY, logoX + radius, logoY)
                ctx.closePath()
                ctx.clip()
                ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
                ctx.restore()
              } else {
                ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize)
              }

              ctx.globalAlpha = 1.0

              canvas.toBlob(async (blob) => {
                if (blob) {
                  try {
                    await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })])
                    toast.success('QR code copied to clipboard 📋')
                    trackToolEvent('qr_code_copy', { type, hasLogo: true })
                  } catch (error) {
                    console.error('Copy error:', error)
                    toast.error('Failed to copy QR code')
                  }
                }
              })
            }
            logoImg.src = styleConfig.logoUrl
          } else {
            canvas.toBlob(async (blob) => {
              if (blob) {
                try {
                  await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })])
                  toast.success('QR code copied to clipboard 📋')
                  trackToolEvent('qr_code_copy', { type, hasLogo: false })
                } catch (error) {
                  console.error('Copy error:', error)
                  toast.error('Failed to copy QR code')
                }
              }
            })
          }
        }
        URL.revokeObjectURL(url)
      }
      img.src = url
    } catch (error) {
      console.error('Copy error:', error)
      toast.error('Failed to copy QR code')
    }
  }

  return (
    <main
      className={css({
        mx: 'auto',
        maxW: '1400px',
        w: 'full',
        px: { base: '4', sm: '6', md: '8' },
        py: { base: '6', sm: '8', md: '10' },
        display: 'flex',
        flexDirection: 'column',
        gap: { base: '6', sm: '8' },
      })}
    >
      {/* Header */}
      <div className={css({ display: 'flex', flexDirection: 'column', gap: '3' })}>
        <div
          className={css({ display: 'flex', alignItems: 'center', gap: { base: '3', sm: '4' } })}
        >
          <div
            className="animate-pulse rounded-xl bg-gradient-to-br from-violet-500 via-purple-500 to-fuchsia-600 p-2.5 shadow-2xl shadow-violet-500/60 sm:rounded-2xl sm:p-4"
            style={{ animationDuration: '2s' }}
          >
            <QrCode className="h-6 w-6 text-white sm:h-8 sm:w-8" />
          </div>
          <div>
            <h1 className="bg-gradient-to-r from-violet-300 via-purple-400 to-fuchsia-300 bg-clip-text text-2xl font-extrabold text-transparent drop-shadow-lg sm:text-3xl md:text-4xl lg:text-5xl">
              QR Code Generator
            </h1>
            <p className="text-sm text-gray-200 sm:text-base md:text-lg">
              Create customizable QR codes for URLs, text, WiFi, and contact cards
            </p>
          </div>
        </div>
      </div>

      <div>
        {/* Input Section */}
        <div
          className={css({ display: 'flex', flexDirection: 'column', gap: { base: '4', md: '6' } })}
        >
          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              QR Code Type
            </h2>
            <div
              className={css({
                display: 'grid',
                gridTemplateColumns: { base: 'repeat(2, 1fr)', sm: 'repeat(4, 1fr)' },
                gap: '3',
              })}
            >
              {(['url', 'text', 'wifi', 'vcard'] as const).map((t) => (
                <Button
                  key={t}
                  onClick={() => {
                    setType(t)
                    trackToolEvent('qr_code_type_change', { type: t })
                  }}
                  variant={type === t ? 'default' : 'outline'}
                  size="sm"
                  className="capitalize"
                >
                  {t}
                </Button>
              ))}
            </div>
          </div>

          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Content
            </h2>
            {type === 'url' && (
              <Field>
                <FieldLabel>URL</FieldLabel>
                <Input
                  placeholder="https://example.com"
                  value={urlInput}
                  onChange={(e) => setUrlInput(e.target.value)}
                />
              </Field>
            )}

            {type === 'text' && (
              <Field>
                <FieldLabel>Text</FieldLabel>
                <Textarea
                  placeholder="Enter any text..."
                  value={textInput}
                  onChange={(e) => setTextInput(e.target.value)}
                  rows={4}
                />
              </Field>
            )}

            {type === 'wifi' && (
              <div className={css({ display: 'flex', flexDirection: 'column', gap: '4' })}>
                <Field>
                  <FieldLabel>Network Name (SSID)</FieldLabel>
                  <Input
                    placeholder="My WiFi Network"
                    value={wifiConfig.ssid}
                    onChange={(e) => setWifiConfig({ ...wifiConfig, ssid: e.target.value })}
                  />
                </Field>
                <Field>
                  <FieldLabel>Password</FieldLabel>
                  <Input
                    type="password"
                    placeholder="WiFi password"
                    value={wifiConfig.password}
                    onChange={(e) => setWifiConfig({ ...wifiConfig, password: e.target.value })}
                  />
                </Field>
                <Field>
                  <FieldLabel>Security</FieldLabel>
                  <div
                    className={css({
                      display: 'grid',
                      gridTemplateColumns: 'repeat(3, 1fr)',
                      gap: '2',
                    })}
                  >
                    {(['WPA', 'WEP', 'nopass'] as const).map((enc) => (
                      <Button
                        key={enc}
                        onClick={() => setWifiConfig({ ...wifiConfig, encryption: enc })}
                        variant={wifiConfig.encryption === enc ? 'default' : 'outline'}
                        size="sm"
                      >
                        {enc === 'nopass' ? 'None' : enc}
                      </Button>
                    ))}
                  </div>
                </Field>
                <label className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                  <input
                    type="checkbox"
                    checked={wifiConfig.hidden}
                    onChange={(e) => setWifiConfig({ ...wifiConfig, hidden: e.target.checked })}
                    className="h-4 w-4 rounded"
                  />
                  <span className="text-sm">Hidden network</span>
                </label>
              </div>
            )}

            {type === 'vcard' && (
              <div className={css({ display: 'flex', flexDirection: 'column', gap: '4' })}>
                <div
                  className={css({
                    display: 'grid',
                    gridTemplateColumns: { base: '1fr', sm: 'repeat(2, 1fr)' },
                    gap: '4',
                  })}
                >
                  <Field>
                    <FieldLabel>First Name</FieldLabel>
                    <Input
                      placeholder="John"
                      value={vcardConfig.firstName}
                      onChange={(e) =>
                        setVcardConfig({ ...vcardConfig, firstName: e.target.value })
                      }
                    />
                  </Field>
                  <Field>
                    <FieldLabel>Last Name</FieldLabel>
                    <Input
                      placeholder="Doe"
                      value={vcardConfig.lastName}
                      onChange={(e) => setVcardConfig({ ...vcardConfig, lastName: e.target.value })}
                    />
                  </Field>
                </div>
                <Field>
                  <FieldLabel>Organization</FieldLabel>
                  <Input
                    placeholder="Company Name"
                    value={vcardConfig.organization}
                    onChange={(e) =>
                      setVcardConfig({ ...vcardConfig, organization: e.target.value })
                    }
                  />
                </Field>
                <Field>
                  <FieldLabel>Phone</FieldLabel>
                  <Input
                    placeholder="+1 234 567 8900"
                    value={vcardConfig.phone}
                    onChange={(e) => setVcardConfig({ ...vcardConfig, phone: e.target.value })}
                  />
                </Field>
                <Field>
                  <FieldLabel>Email</FieldLabel>
                  <Input
                    type="email"
                    placeholder="john@example.com"
                    value={vcardConfig.email}
                    onChange={(e) => setVcardConfig({ ...vcardConfig, email: e.target.value })}
                  />
                </Field>
                <Field>
                  <FieldLabel>Website</FieldLabel>
                  <Input
                    placeholder="https://example.com"
                    value={vcardConfig.website}
                    onChange={(e) => setVcardConfig({ ...vcardConfig, website: e.target.value })}
                  />
                </Field>
                <Field>
                  <FieldLabel>Address</FieldLabel>
                  <Input
                    placeholder="123 Main St, City, Country"
                    value={vcardConfig.address}
                    onChange={(e) => setVcardConfig({ ...vcardConfig, address: e.target.value })}
                  />
                </Field>
              </div>
            )}
          </div>

          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Customization
            </h2>
            <div className={css({ display: 'flex', flexDirection: 'column', gap: '4' })}>
              <div
                className={css({
                  display: 'grid',
                  gridTemplateColumns: { base: '1fr', sm: 'repeat(2, 1fr)' },
                  gap: '4',
                })}
              >
                <Field>
                  <FieldLabel>Foreground Color</FieldLabel>
                  <div className={css({ display: 'flex', gap: '2' })}>
                    <Input
                      type="color"
                      value={fgColor}
                      onChange={(e) => setFgColor(e.target.value)}
                      className="h-10 w-20 cursor-pointer"
                    />
                    <Input
                      value={fgColor}
                      onChange={(e) => setFgColor(e.target.value)}
                      className="flex-1"
                    />
                  </div>
                </Field>
                <Field>
                  <FieldLabel>Background Color</FieldLabel>
                  <div className={css({ display: 'flex', gap: '2' })}>
                    <Input
                      type="color"
                      value={bgColor}
                      onChange={(e) => setBgColor(e.target.value)}
                      className="h-10 w-20 cursor-pointer"
                    />
                    <Input
                      value={bgColor}
                      onChange={(e) => setBgColor(e.target.value)}
                      className="flex-1"
                    />
                  </div>
                </Field>
              </div>
              <Field>
                <FieldLabel>Size: {size}px</FieldLabel>
                <input
                  type="range"
                  min="128"
                  max="512"
                  step="32"
                  value={size}
                  onChange={(e) => setSize(Number(e.target.value))}
                  className="w-full"
                />
                <div
                  className={css({
                    mt: '1',
                    display: 'flex',
                    justifyContent: 'space-between',
                    fontSize: 'xs',
                    color: 'gray.400',
                  })}
                >
                  <span>128px</span>
                  <span>512px</span>
                </div>
              </Field>
              <label className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                <input
                  type="checkbox"
                  checked={includeMargin}
                  onChange={(e) => setIncludeMargin(e.target.checked)}
                  className="h-4 w-4 rounded"
                />
                <span className="text-sm">Include margin</span>
              </label>
            </div>
          </div>

          {/* Style Presets Section */}
          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Style Presets
            </h2>
            <div
              className={css({
                display: 'grid',
                gridTemplateColumns: {
                  base: 'repeat(2, 1fr)',
                  sm: 'repeat(3, 1fr)',
                  md: 'repeat(6, 1fr)',
                },
                gap: '3',
              })}
            >
              {(
                ['classic', 'modern', 'branded', 'minimalist', 'professional', 'vibrant'] as const
              ).map((preset) => (
                <Button
                  key={preset}
                  onClick={() => applyStylePreset(preset)}
                  variant={styleConfig.preset === preset ? 'default' : 'outline'}
                  size="sm"
                  className="capitalize"
                >
                  {preset}
                </Button>
              ))}
            </div>
          </div>

          {/* Logo Upload Section */}
          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Logo / Icon
            </h2>
            <div className={css({ display: 'flex', flexDirection: 'column', gap: '3' })}>
              {!styleConfig.hasLogo ? (
                <div>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleLogoUpload}
                    className="hidden"
                  />
                  <Button
                    onClick={() => fileInputRef.current?.click()}
                    variant="outline"
                    className="w-full"
                  >
                    <Upload className="mr-2 h-4 w-4" />
                    Upload Logo
                  </Button>
                  <p
                    className={css({
                      mt: '2',
                      fontSize: 'sm',
                      color: 'gray.400',
                      textAlign: 'center',
                    })}
                  >
                    Max 5MB • PNG, JPG, SVG supported
                  </p>
                </div>
              ) : (
                <div className={css({ display: 'flex', flexDirection: 'column', gap: '3' })}>
                  <div
                    className={css({
                      display: 'flex',
                      alignItems: 'center',
                      gap: '3',
                      p: '3',
                      rounded: 'lg',
                      border: '1px solid',
                      borderColor: 'violet.500/30',
                      bg: 'rgba(139, 92, 246, 0.1)',
                    })}
                  >
                    <ImageIcon className="h-5 w-5 text-violet-400" />
                    <span className="flex-1 text-sm text-gray-200 truncate">
                      {logoFile?.name || 'Logo uploaded'}
                    </span>
                    <Button onClick={removeLogo} size="sm" variant="ghost" className="h-8 w-8 p-0">
                      <X className="h-4 w-4" />
                    </Button>
                  </div>

                  <Field>
                    <FieldLabel>Logo Size: {styleConfig.logoSize}%</FieldLabel>
                    <input
                      type="range"
                      min="10"
                      max="40"
                      step="5"
                      value={styleConfig.logoSize}
                      onChange={(e) =>
                        setStyleConfig({ ...styleConfig, logoSize: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </Field>

                  <Field>
                    <FieldLabel>Logo Opacity: {styleConfig.logoOpacity}%</FieldLabel>
                    <input
                      type="range"
                      min="50"
                      max="100"
                      step="10"
                      value={styleConfig.logoOpacity}
                      onChange={(e) =>
                        setStyleConfig({ ...styleConfig, logoOpacity: Number(e.target.value) })
                      }
                      className="w-full"
                    />
                  </Field>

                  <Field>
                    <FieldLabel>Logo Mask</FieldLabel>
                    <div
                      className={css({
                        display: 'grid',
                        gridTemplateColumns: 'repeat(4, 1fr)',
                        gap: '2',
                      })}
                    >
                      {(['none', 'circle', 'square', 'rounded'] as const).map((mask) => (
                        <Button
                          key={mask}
                          onClick={() => setStyleConfig({ ...styleConfig, logoMask: mask })}
                          variant={styleConfig.logoMask === mask ? 'default' : 'outline'}
                          size="sm"
                          className="capitalize"
                        >
                          {mask}
                        </Button>
                      ))}
                    </div>
                  </Field>
                </div>
              )}
            </div>
          </div>

          {/* Bulk Generation Section */}
          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Bulk QR Generation
            </h2>
            <p className={css({ fontSize: 'sm', color: 'gray.400' })}>
              Generate up to 500 QR codes at once from a CSV file
            </p>

            <div className={css({ display: 'flex', flexDirection: 'column', gap: '3' })}>
              {!showBulkMode ? (
                <>
                  <input
                    ref={csvInputRef}
                    type="file"
                    accept=".csv"
                    onChange={handleCSVUpload}
                    className="hidden"
                  />
                  <div
                    className={css({
                      display: 'grid',
                      gridTemplateColumns: { base: '1fr', sm: 'repeat(2, 1fr)' },
                      gap: '3',
                    })}
                  >
                    <Button
                      onClick={() => csvInputRef.current?.click()}
                      variant="default"
                      className="w-full"
                    >
                      <FileUp className="mr-2 h-4 w-4" />
                      Upload CSV
                    </Button>
                    <Button onClick={downloadSampleCSV} variant="outline" className="w-full">
                      <FileDown className="mr-2 h-4 w-4" />
                      Download Sample
                    </Button>
                  </div>
                  <div
                    className={css({
                      p: '3',
                      rounded: 'lg',
                      border: '1px solid',
                      borderColor: 'violet.500/30',
                      bg: 'rgba(139, 92, 246, 0.05)',
                    })}
                  >
                    <p className={css({ fontSize: 'sm', color: 'gray.300', mb: '2' })}>
                      CSV Format:
                    </p>
                    <code
                      className={css({
                        fontSize: 'xs',
                        color: 'violet.300',
                        display: 'block',
                        fontFamily: 'mono',
                      })}
                    >
                      type,content,label,color
                      <br />
                      url,https://example.com,Website,#000000
                    </code>
                  </div>
                </>
              ) : (
                <>
                  <div
                    className={css({
                      p: '4',
                      rounded: 'lg',
                      border: '1px solid',
                      borderColor: 'violet.500/30',
                      bg: 'rgba(139, 92, 246, 0.1)',
                    })}
                  >
                    <div
                      className={css({ display: 'flex', justifyContent: 'space-between', mb: '2' })}
                    >
                      <span className={css({ fontSize: 'sm', color: 'gray.200' })}>
                        {bulkState.items.length} QR codes ready
                      </span>
                      {bulkState.isGenerating && (
                        <span className={css({ fontSize: 'sm', color: 'violet.300' })}>
                          {bulkState.progress}%
                        </span>
                      )}
                    </div>
                    {bulkState.isGenerating && (
                      <div
                        className={css({
                          w: 'full',
                          h: '2',
                          bg: 'gray.700',
                          rounded: 'full',
                          overflow: 'hidden',
                        })}
                      >
                        <div
                          className={css({
                            h: 'full',
                            bg: 'violet.500',
                            transition: 'width 0.3s ease',
                          })}
                          style={{ width: `${bulkState.progress}%` }}
                        />
                      </div>
                    )}
                  </div>
                  <div
                    className={css({
                      display: 'grid',
                      gridTemplateColumns: { base: '1fr', sm: 'repeat(2, 1fr)' },
                      gap: '3',
                    })}
                  >
                    <Button
                      onClick={generateBulkQRCodes}
                      disabled={bulkState.isGenerating || bulkState.items.length === 0}
                      variant="default"
                      className="w-full"
                    >
                      <Download className="mr-2 h-4 w-4" />
                      Generate & Download ZIP
                    </Button>
                    <Button
                      onClick={clearBulkQueue}
                      disabled={bulkState.isGenerating}
                      variant="outline"
                      className="w-full"
                    >
                      <X className="mr-2 h-4 w-4" />
                      Clear Queue
                    </Button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>

        {/* Preview Section */}
        <div
          className={css({ display: 'flex', flexDirection: 'column', gap: { base: '4', md: '6' } })}
        >
          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Preview
            </h2>
            <div
              className={css({
                display: 'flex',
                minH: '300px',
                alignItems: 'center',
                justifyContent: 'center',
                rounded: 'lg',
                border: '2px dashed',
                borderColor: 'violet.500/30',
                p: '8',
              })}
              style={{ backgroundColor: bgColor }}
            >
              {hasValidInput ? (
                <div ref={qrRef} className={css({ position: 'relative', display: 'inline-block' })}>
                  <QRCodeSVG
                    id="qr-code-svg"
                    value={qrValue}
                    size={size}
                    bgColor={bgColor}
                    fgColor={fgColor}
                    level="H"
                    includeMargin={includeMargin}
                  />
                  {styleConfig.hasLogo && styleConfig.logoUrl && (
                    <div
                      className={css({
                        position: 'absolute',
                        top: '50%',
                        left: '50%',
                        transform: 'translate(-50%, -50%)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                      })}
                      style={{
                        width: `${(size * styleConfig.logoSize) / 100}px`,
                        height: `${(size * styleConfig.logoSize) / 100}px`,
                        opacity: styleConfig.logoOpacity / 100,
                      }}
                    >
                      <img
                        src={styleConfig.logoUrl}
                        alt="Logo"
                        className={css({
                          width: '100%',
                          height: '100%',
                          objectFit: 'contain',
                        })}
                        style={{
                          borderRadius:
                            styleConfig.logoMask === 'circle'
                              ? '50%'
                              : styleConfig.logoMask === 'rounded'
                                ? '8px'
                                : styleConfig.logoMask === 'square'
                                  ? '0'
                                  : '0',
                        }}
                      />
                    </div>
                  )}
                </div>
              ) : (
                <div className={css({ textAlign: 'center' })}>
                  <QrCode
                    className={css({
                      mx: 'auto',
                      h: '16',
                      w: '16',
                      color: 'gray.400',
                      opacity: 0.5,
                    })}
                  />
                  <p className={css({ mt: '2', color: 'gray.400' })}>
                    Enter content to generate QR code
                  </p>
                </div>
              )}
            </div>
          </div>

          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '4',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'lg', sm: 'xl' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Actions
            </h2>
            <div className={css({ display: 'flex', flexWrap: 'wrap', gap: '3' })}>
              <Button
                onClick={() => downloadQRCode('png')}
                disabled={!hasValidInput}
                className={css({ flex: '1' })}
              >
                <Download className="mr-2 h-4 w-4" />
                Download PNG
              </Button>
              <Button
                onClick={() => downloadQRCode('svg')}
                disabled={!hasValidInput}
                variant="outline"
                className={css({ flex: '1' })}
              >
                <Download className="mr-2 h-4 w-4" />
                Download SVG
              </Button>
              <Button
                onClick={copyQRCode}
                disabled={!hasValidInput}
                variant="outline"
                className={css({ flex: '1' })}
              >
                <Copy className="mr-2 h-4 w-4" />
                Copy Image
              </Button>
            </div>
          </div>

          <div
            className={css({
              rounded: { base: 'xl', sm: '2xl' },
              border: '2px solid',
              borderColor: 'violet.500/20',
              bg: 'rgba(17, 24, 39, 0.5)',
              p: { base: '4', sm: '5', md: '6' },
              backdropFilter: 'blur(16px)',
              display: 'flex',
              flexDirection: 'column',
              gap: '3',
            })}
          >
            <h2
              className={css({
                fontSize: { base: 'base', sm: 'lg' },
                fontWeight: 'bold',
                color: 'violet.300',
              })}
            >
              Features
            </h2>
            <div className={css({ display: 'flex', flexDirection: 'column', gap: '2' })}>
              <div className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                <Badge>Multiple Types</Badge>
                <span className={css({ fontSize: 'sm', color: 'gray.400' })}>
                  URL, Text, WiFi, vCard support
                </span>
              </div>
              <div className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                <Badge>Customizable</Badge>
                <span className={css({ fontSize: 'sm', color: 'gray.400' })}>
                  Colors, size, and margins
                </span>
              </div>
              <div className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                <Badge>High Resolution</Badge>
                <span className={css({ fontSize: 'sm', color: 'gray.400' })}>
                  Up to 512px with error correction
                </span>
              </div>
              <div className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                <Badge>Multiple Formats</Badge>
                <span className={css({ fontSize: 'sm', color: 'gray.400' })}>
                  PNG and SVG exports
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <FAQAccordion faqs={faqs} />
      <RelatedTools currentToolPath="/tools/qr-code" category="productivity" />
      <ToolRating toolId="/tools/qr-code" toolName="QR Code Generator" />
    </main>
  )
}
