import type { CronPreset } from './types'

export const CRON_PRESETS: CronPreset[] = [
  // Common patterns
  {
    name: 'Every minute',
    description: 'Runs every minute',
    expression: '* * * * *',
    config: {
      minute: '*',
      hour: '*',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'common',
  },
  {
    name: 'Every 5 minutes',
    description: 'Runs every 5 minutes',
    expression: '*/5 * * * *',
    config: {
      minute: '*/5',
      hour: '*',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'common',
  },
  {
    name: 'Every 15 minutes',
    description: 'Runs every 15 minutes',
    expression: '*/15 * * * *',
    config: {
      minute: '*/15',
      hour: '*',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'common',
  },
  {
    name: 'Every 30 minutes',
    description: 'Runs every 30 minutes',
    expression: '*/30 * * * *',
    config: {
      minute: '*/30',
      hour: '*',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'common',
  },

  // Hourly patterns
  {
    name: 'Every hour',
    description: 'Runs at the start of every hour',
    expression: '0 * * * *',
    config: {
      minute: '0',
      hour: '*',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'hourly',
  },
  {
    name: 'Every 2 hours',
    description: 'Runs every 2 hours',
    expression: '0 */2 * * *',
    config: {
      minute: '0',
      hour: '*/2',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'hourly',
  },
  {
    name: 'Every 4 hours',
    description: 'Runs every 4 hours',
    expression: '0 */4 * * *',
    config: {
      minute: '0',
      hour: '*/4',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'hourly',
  },
  {
    name: 'Every 6 hours',
    description: 'Runs every 6 hours',
    expression: '0 */6 * * *',
    config: {
      minute: '0',
      hour: '*/6',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'hourly',
  },
  {
    name: 'Every 12 hours',
    description: 'Runs twice a day',
    expression: '0 */12 * * *',
    config: {
      minute: '0',
      hour: '*/12',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'hourly',
  },

  // Daily patterns
  {
    name: 'Daily at midnight',
    description: 'Runs at 12:00 AM every day',
    expression: '0 0 * * *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'daily',
  },
  {
    name: 'Daily at noon',
    description: 'Runs at 12:00 PM every day',
    expression: '0 12 * * *',
    config: {
      minute: '0',
      hour: '12',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'daily',
  },
  {
    name: 'Daily at 6 AM',
    description: 'Runs at 6:00 AM every day',
    expression: '0 6 * * *',
    config: {
      minute: '0',
      hour: '6',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'daily',
  },
  {
    name: 'Daily at 9 PM',
    description: 'Runs at 9:00 PM every day',
    expression: '0 21 * * *',
    config: {
      minute: '0',
      hour: '21',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'daily',
  },
  {
    name: 'Twice daily (9 AM & 9 PM)',
    description: 'Runs at 9:00 AM and 9:00 PM',
    expression: '0 9,21 * * *',
    config: {
      minute: '0',
      hour: '9,21',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'daily',
  },

  // Weekly patterns
  {
    name: 'Every Monday at 9 AM',
    description: 'Runs every Monday at 9:00 AM',
    expression: '0 9 * * 1',
    config: {
      minute: '0',
      hour: '9',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '1',
    },
    category: 'weekly',
  },
  {
    name: 'Every Friday at 5 PM',
    description: 'Runs every Friday at 5:00 PM',
    expression: '0 17 * * 5',
    config: {
      minute: '0',
      hour: '17',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '5',
    },
    category: 'weekly',
  },
  {
    name: 'Every Sunday at midnight',
    description: 'Runs every Sunday at 12:00 AM',
    expression: '0 0 * * 0',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '0',
    },
    category: 'weekly',
  },
  {
    name: 'Weekdays at 9 AM',
    description: 'Runs Monday-Friday at 9:00 AM',
    expression: '0 9 * * 1-5',
    config: {
      minute: '0',
      hour: '9',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '1-5',
    },
    category: 'weekly',
  },
  {
    name: 'Weekends at noon',
    description: 'Runs Saturday-Sunday at 12:00 PM',
    expression: '0 12 * * 0,6',
    config: {
      minute: '0',
      hour: '12',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '0,6',
    },
    category: 'weekly',
  },

  // Monthly patterns
  {
    name: 'First day of month',
    description: 'Runs at midnight on the 1st of every month',
    expression: '0 0 1 * *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '1',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'monthly',
  },
  {
    name: 'Last day of month',
    description: 'Runs at midnight on the last day of every month (Quartz only)',
    expression: '0 0 L * *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: 'L',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'monthly',
  },
  {
    name: '15th of every month',
    description: 'Runs at midnight on the 15th of every month',
    expression: '0 0 15 * *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '15',
      month: '*',
      dayOfWeek: '*',
    },
    category: 'monthly',
  },
  {
    name: 'First Monday of month',
    description: 'Runs on the first Monday of every month',
    expression: '0 9 * * 1#1',
    config: {
      minute: '0',
      hour: '9',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '1#1',
    },
    category: 'monthly',
  },

  // Advanced patterns
  {
    name: 'Business hours (9 AM - 5 PM)',
    description: 'Runs every hour from 9 AM to 5 PM on weekdays',
    expression: '0 9-17 * * 1-5',
    config: {
      minute: '0',
      hour: '9-17',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '1-5',
    },
    category: 'advanced',
  },
  {
    name: 'Every quarter (Jan/Apr/Jul/Oct)',
    description: 'Runs at midnight on the 1st of every quarter',
    expression: '0 0 1 1,4,7,10 *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '1',
      month: '1,4,7,10',
      dayOfWeek: '*',
    },
    category: 'advanced',
  },
  {
    name: 'Every 10 minutes during work hours',
    description: 'Runs every 10 minutes from 8 AM to 6 PM on weekdays',
    expression: '*/10 8-18 * * 1-5',
    config: {
      minute: '*/10',
      hour: '8-18',
      dayOfMonth: '*',
      month: '*',
      dayOfWeek: '1-5',
    },
    category: 'advanced',
  },
  {
    name: 'Yearly (January 1st)',
    description: 'Runs at midnight on January 1st every year',
    expression: '0 0 1 1 *',
    config: {
      minute: '0',
      hour: '0',
      dayOfMonth: '1',
      month: '1',
      dayOfWeek: '*',
    },
    category: 'advanced',
  },
]

export const PRESET_CATEGORIES = [
  { value: 'common', label: 'Common' },
  { value: 'hourly', label: 'Hourly' },
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
  { value: 'advanced', label: 'Advanced' },
] as const
