'use client'

import { motion } from 'framer-motion'
import { Check, Copy, Download, FileText, Lightbulb, Minimize2, Sparkles, Type } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { trackToolEvent } from '@/lib/analytics'
import { css } from '@/styled-system/css'

interface SummaryResult {
  summary: string
  highlights: string[]
  stats: {
    wordCount: number
    charCount: number
    originalWordCount: number
    originalCharCount: number
  }
}

type SummaryLength = 'short' | 'medium' | 'long'
type SummaryFormat = 'bullets' | 'paragraph'

function TextSummarizerContent() {
  const [text, setText] = useState('')
  const [length, setLength] = useState<SummaryLength>('medium')
  const [format, setFormat] = useState<SummaryFormat>('paragraph')
  const [result, setResult] = useState<SummaryResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  // Track page visit
  useEffect(() => {
    trackToolEvent('text_summarizer_open', {})
  }, [])

  const handleSummarize = async () => {
    if (!text.trim()) {
      toast.error('Please enter text to summarize')
      return
    }

    if (text.trim().split(/\s+/).length < 50) {
      toast.error('Please enter at least 50 words to generate a meaningful summary')
      return
    }

    setLoading(true)
    setResult(null)

    try {
      const response = await fetch('/api/text-summarizer', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          text: text.trim(),
          length,
          format,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate summary')
      }

      setResult({
        summary: data.summary,
        highlights: data.highlights || [],
        stats: data.stats,
      })

      toast.success('Summary generated successfully!')

      trackToolEvent('text_summarizer_summarize', {
        length,
        format,
        originalWords: data.stats.originalWordCount,
        summaryWords: data.stats.wordCount,
        tokens: data.usage?.total_tokens || 0,
      })
    } catch (error) {
      console.error('Error generating summary:', error)
      const errorMessage = error instanceof Error ? error.message : 'Failed to generate summary'
      toast.error(errorMessage)

      trackToolEvent('text_summarizer_error', {
        error: 'generation_failed',
        message: errorMessage,
      })
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (result) {
      navigator.clipboard.writeText(result.summary)
      toast.success('Summary copied to clipboard')
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)

      trackToolEvent('text_summarizer_copy', { format })
    }
  }

  const handleDownload = (fileFormat: 'txt' | 'md') => {
    if (!result) return

    let content = ''
    const filename = `summary-${Date.now()}.${fileFormat}`

    if (fileFormat === 'md') {
      content = `# Summary\n\n${result.summary}\n\n## Key Highlights\n\n${result.highlights.map((h) => `- ${h}`).join('\n')}\n\n---\n\n*Generated by Supertool Text Summarizer*`
    } else {
      content = `Summary:\n\n${result.summary}\n\nKey Highlights:\n\n${result.highlights.map((h) => `• ${h}`).join('\n')}\n\n---\n\nGenerated by Supertool Text Summarizer`
    }

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    toast.success(`Downloaded as ${filename}`)

    trackToolEvent('text_summarizer_download', { format: fileFormat })
  }

  const handleClear = () => {
    setText('')
    setResult(null)
    setCopied(false)
  }

  const wordCount = text
    .trim()
    .split(/\s+/)
    .filter((word) => word.length > 0).length
  const charCount = text.length

  return (
    <main
      className={css({
        mx: 'auto',
        maxW: '7xl',
        w: 'full',
        px: { base: '4', sm: '6', md: '8' },
        py: { base: '6', sm: '8', md: '10' },
        spaceY: { base: '6', sm: '8', md: '10' },
      })}
    >
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className={css({ textAlign: 'center', spaceY: '4' })}
      >
        <div
          className={css({
            display: 'inline-flex',
            alignItems: 'center',
            gap: '3',
            rounded: 'full',
            border: '1px solid',
            borderColor: 'blue.500/30',
            bg: 'blue.500/10',
            px: '5',
            py: '2',
            backdropFilter: 'blur(8px)',
          })}
        >
          <Minimize2 className={css({ h: '5', w: '5', color: 'blue.400' })} />
          <span className={css({ fontSize: 'sm', fontWeight: 'semibold', color: 'blue.300' })}>
            AI-Powered • Multi-Format • Adjustable Length
          </span>
        </div>

        <h1
          className={css({
            fontSize: { base: '4xl', sm: '5xl', md: '6xl' },
            fontWeight: 'extrabold',
            bgGradient: 'to-r',
            gradientFrom: 'blue.400',
            gradientVia: 'cyan.400',
            gradientTo: 'teal.400',
            bgClip: 'text',
          })}
          style={{
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
          }}
        >
          Text Summarizer
        </h1>

        <p
          className={css({
            mx: 'auto',
            maxW: '3xl',
            fontSize: { base: 'lg', sm: 'xl' },
            color: 'gray.400',
          })}
        >
          Transform long articles, documents, and text into concise summaries with AI. Generate
          bullet points or paragraphs, adjust length, and extract key highlights instantly.
        </p>
      </motion.div>

      {/* Input Section */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1, duration: 0.5 }}
      >
        <Card
          className={css({
            border: '1px solid',
            borderColor: 'blue.500/20',
            bg: 'gray.900/50',
            backdropFilter: 'blur(16px)',
          })}
        >
          <CardHeader>
            <CardTitle>Text to Summarize</CardTitle>
            <CardDescription>
              Paste your text below (minimum 50 words for meaningful summaries)
            </CardDescription>
          </CardHeader>
          <CardContent className={css({ spaceY: '4' })}>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste your article, document, or any long-form text here. The AI will analyze and create a concise summary capturing the main ideas and key points..."
              className={css({
                minH: '64',
                bg: 'gray.800/50',
                border: '1px solid',
                borderColor: 'gray.700',
                color: 'gray.200',
                fontSize: 'sm',
                lineHeight: '1.6',
                resize: 'vertical',
                _focus: {
                  borderColor: 'blue.500/50',
                  outline: 'none',
                },
              })}
            />

            {/* Stats */}
            <div className={css({ display: 'flex', gap: '4', fontSize: 'sm', color: 'gray.400' })}>
              <span>
                <Type className={css({ display: 'inline', h: '4', w: '4', mr: '1' })} />
                {wordCount} words
              </span>
              <span>
                <FileText className={css({ display: 'inline', h: '4', w: '4', mr: '1' })} />
                {charCount} characters
              </span>
            </div>

            {/* Length Selection */}
            <div className={css({ spaceY: '3' })}>
              <div className={css({ fontSize: 'sm', fontWeight: 'medium', color: 'gray.300' })}>
                Summary Length
              </div>
              <div className={css({ display: 'flex', gap: '2', flexWrap: 'wrap' })}>
                {(['short', 'medium', 'long'] as SummaryLength[]).map((len) => {
                  const isActive = length === len
                  return (
                    <Button
                      key={len}
                      onClick={() => setLength(len)}
                      size="sm"
                      className={css({
                        gap: '2',
                        bg: isActive ? 'blue.500/20' : 'gray.800/50',
                        border: '1px solid',
                        borderColor: isActive ? 'blue.500/50' : 'gray.700/50',
                        color: isActive ? 'blue.300' : 'gray.400',
                        textTransform: 'capitalize',
                        transition: 'all 0.2s',
                        _hover: {
                          bg: isActive ? 'blue.500/30' : 'gray.800',
                          borderColor: isActive ? 'blue.500/70' : 'gray.600',
                        },
                      })}
                    >
                      {len.charAt(0).toUpperCase() + len.slice(1)}
                    </Button>
                  )
                })}
              </div>
            </div>

            {/* Format Selection */}
            <div className={css({ spaceY: '3' })}>
              <div className={css({ fontSize: 'sm', fontWeight: 'medium', color: 'gray.300' })}>
                Summary Format
              </div>
              <div className={css({ display: 'flex', gap: '2', flexWrap: 'wrap' })}>
                {(['paragraph', 'bullets'] as SummaryFormat[]).map((fmt) => {
                  const isActive = format === fmt
                  return (
                    <Button
                      key={fmt}
                      onClick={() => setFormat(fmt)}
                      size="sm"
                      className={css({
                        gap: '2',
                        bg: isActive ? 'cyan.500/20' : 'gray.800/50',
                        border: '1px solid',
                        borderColor: isActive ? 'cyan.500/50' : 'gray.700/50',
                        color: isActive ? 'cyan.300' : 'gray.400',
                        textTransform: 'capitalize',
                        transition: 'all 0.2s',
                        _hover: {
                          bg: isActive ? 'cyan.500/30' : 'gray.800',
                          borderColor: isActive ? 'cyan.500/70' : 'gray.600',
                        },
                      })}
                    >
                      {fmt === 'bullets' ? 'Bullet Points' : 'Paragraph'}
                    </Button>
                  )
                })}
              </div>
            </div>

            <div className={css({ display: 'flex', gap: '3' })}>
              <Button
                onClick={handleSummarize}
                disabled={loading || !text.trim() || wordCount < 50}
                className={css({
                  flex: '1',
                  gap: '2',
                  h: '12',
                  bg: 'blue.500',
                  color: 'white',
                  fontWeight: 'semibold',
                  _hover: { bg: 'blue.600' },
                  _disabled: { opacity: '0.5', cursor: 'not-allowed' },
                })}
              >
                {loading ? (
                  <>
                    <div
                      className={css({
                        display: 'inline-block',
                        rounded: 'full',
                        border: '2px solid',
                        borderColor: 'white',
                        borderTopColor: 'transparent',
                        h: '5',
                        w: '5',
                        animation: 'spin 1s linear infinite',
                      })}
                    />
                    Summarizing...
                  </>
                ) : (
                  <>
                    <Sparkles className={css({ h: '5', w: '5' })} />
                    Summarize Text
                  </>
                )}
              </Button>

              {result && (
                <Button
                  onClick={handleClear}
                  className={css({
                    gap: '2',
                    bg: 'gray.800',
                    color: 'gray.300',
                    _hover: { bg: 'gray.700' },
                  })}
                >
                  Clear
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Summary Result */}
      {result && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.5 }}
        >
          <Card
            className={css({
              border: '1px solid',
              borderColor: 'green.500/20',
              bg: 'gray.900/50',
              backdropFilter: 'blur(16px)',
            })}
          >
            <CardHeader>
              <div
                className={css({
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  flexWrap: 'wrap',
                  gap: '3',
                })}
              >
                <div className={css({ display: 'flex', alignItems: 'center', gap: '2' })}>
                  <Check className={css({ h: '5', w: '5', color: 'green.400' })} />
                  <CardTitle>Summary</CardTitle>
                  <Badge
                    className={css({
                      bg: 'blue.500/20',
                      color: 'blue.300',
                      border: '1px solid',
                      borderColor: 'blue.500/30',
                      textTransform: 'uppercase',
                    })}
                  >
                    {format === 'bullets' ? 'Bullet Points' : 'Paragraph'}
                  </Badge>
                </div>
                <div className={css({ display: 'flex', gap: '2' })}>
                  <Button
                    onClick={handleCopy}
                    size="sm"
                    className={css({
                      gap: '2',
                      bg: copied ? 'green.500/20' : 'gray.800',
                      color: copied ? 'green.400' : 'gray.400',
                      _hover: {
                        bg: copied ? 'green.500/30' : 'gray.700',
                        color: copied ? 'green.400' : 'blue.400',
                      },
                    })}
                  >
                    {copied ? (
                      <>
                        <Check className={css({ h: '4', w: '4' })} />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className={css({ h: '4', w: '4' })} />
                        Copy
                      </>
                    )}
                  </Button>
                  <Button
                    onClick={() => handleDownload('txt')}
                    size="sm"
                    className={css({
                      gap: '2',
                      bg: 'gray.800',
                      color: 'gray.400',
                      _hover: {
                        bg: 'gray.700',
                        color: 'blue.400',
                      },
                    })}
                  >
                    <Download className={css({ h: '4', w: '4' })} />
                    TXT
                  </Button>
                  <Button
                    onClick={() => handleDownload('md')}
                    size="sm"
                    className={css({
                      gap: '2',
                      bg: 'gray.800',
                      color: 'gray.400',
                      _hover: {
                        bg: 'gray.700',
                        color: 'blue.400',
                      },
                    })}
                  >
                    <Download className={css({ h: '4', w: '4' })} />
                    MD
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent className={css({ spaceY: '4' })}>
              {/* Summary Text */}
              <div
                className={css({
                  rounded: 'lg',
                  border: '1px solid',
                  borderColor: 'gray.700',
                  bg: 'gray.950',
                  p: '4',
                })}
              >
                <p
                  className={css({
                    fontSize: 'sm',
                    color: 'gray.200',
                    lineHeight: '1.7',
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-word',
                  })}
                >
                  {result.summary}
                </p>
              </div>

              {/* Stats */}
              <div
                className={css({
                  display: 'flex',
                  gap: '4',
                  flexWrap: 'wrap',
                  fontSize: 'sm',
                  color: 'gray.400',
                })}
              >
                <span>
                  Original: {result.stats.originalWordCount} words, {result.stats.originalCharCount}{' '}
                  characters
                </span>
                <span>•</span>
                <span>
                  Summary: {result.stats.wordCount} words, {result.stats.charCount} characters
                </span>
                <span>•</span>
                <span>
                  Reduction:{' '}
                  {Math.round((1 - result.stats.wordCount / result.stats.originalWordCount) * 100)}%
                </span>
              </div>

              {/* Key Highlights */}
              {result.highlights.length > 0 && (
                <div
                  className={css({
                    rounded: 'lg',
                    border: '1px solid',
                    borderColor: 'cyan.500/20',
                    bg: 'cyan.500/5',
                    p: '4',
                  })}
                >
                  <div className={css({ display: 'flex', alignItems: 'start', gap: '3' })}>
                    <Lightbulb
                      className={css({ h: '5', w: '5', color: 'cyan.400', flexShrink: '0' })}
                    />
                    <div className={css({ spaceY: '2', flex: '1' })}>
                      <h4
                        className={css({
                          fontSize: 'sm',
                          fontWeight: 'semibold',
                          color: 'cyan.300',
                        })}
                      >
                        Key Highlights
                      </h4>
                      <ul className={css({ spaceY: '2', fontSize: 'sm', color: 'gray.400' })}>
                        {result.highlights.map((highlight, index) => (
                          <li key={index}>• {highlight}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Pro Tips */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: result ? 0.3 : 0.2, duration: 0.5 }}
      >
        <Card
          className={css({
            border: '1px solid',
            borderColor: 'purple.500/20',
            bg: 'purple.500/5',
            backdropFilter: 'blur(16px)',
          })}
        >
          <CardContent className={css({ py: '6' })}>
            <div className={css({ display: 'flex', alignItems: 'start', gap: '4' })}>
              <Sparkles className={css({ h: '6', w: '6', color: 'purple.400', flexShrink: '0' })} />
              <div className={css({ spaceY: '2' })}>
                <h3
                  className={css({ fontSize: 'lg', fontWeight: 'semibold', color: 'purple.300' })}
                >
                  Pro Tips
                </h3>
                <ul className={css({ spaceY: '2', fontSize: 'sm', color: 'gray.400' })}>
                  <li>
                    • For best results, provide text with at least 50 words - longer content
                    generates more comprehensive summaries
                  </li>
                  <li>
                    • Choose "Bullet Points" for quick takeaways and action items, "Paragraph" for
                    narrative summaries
                  </li>
                  <li>
                    • Adjust length based on your needs: Short for quick overviews, Long for
                    detailed analysis
                  </li>
                  <li>
                    • The AI extracts key highlights automatically - perfect for meeting notes and
                    research papers
                  </li>
                  <li>
                    • Download summaries in TXT or Markdown format for easy sharing and storage
                  </li>
                  <li>
                    • All processing uses OpenAI GPT models - ensure your API key is configured
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </main>
  )
}

export default function TextSummarizerPage() {
  return <TextSummarizerContent />
}
