import type { Metadata } from 'next'
import { generateToolMetadata } from '@/lib/data/metadata'

export const metadata: Metadata = generateToolMetadata({
  title: 'Free Resume Builder - Create Professional ATS-Friendly Resumes Online',
  description:
    'Build professional resumes with 10 designer templates. Free resume builder with ATS optimization, real-time scoring, and PDF export. Choose from Modern, Classic, Tech, Executive, Creative, Minimal, Elegant, and more. Create job-winning resumes in minutes with live preview and instant download.',
  keywords: [
    'resume builder',
    'free resume builder',
    'resume maker',
    'CV builder',
    'curriculum vitae builder',
    'professional resume',
    'ATS resume',
    'ATS-friendly resume',
    'ATS resume builder',
    'resume templates',
    'free resume templates',
    'modern resume',
    'creative resume',
    'executive resume',
    'tech resume',
    'minimal resume',
    'elegant resume',
    'classic resume',
    'resume creator',
    'online resume builder',
    'resume generator',
    'job application resume',
    'career resume',
    'professional CV',
    'resume design',
    'resume formatting',
    'resume PDF',
    'download resume',
    'resume export',
    'resume writer',
    'resume editor',
    'live resume preview',
    'resume checker',
    'ATS score',
    'resume optimization',
    'job search tool',
    'career tool',
    'interview resume',
    'resume for job',
    'create resume online',
    'build resume free',
    'resume with photo',
    'one-page resume',
    'two-column resume',
    'compact resume',
    'resume for developers',
    'resume for designers',
    'resume for executives',
    'resume for managers',
    'student resume',
    'entry-level resume',
    'experienced professional resume',
  ],
  category: 'productivity',
  path: '/tools/productivity/resume-builder',
})

export default function ResumeBuilderLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
